In [1]:
# ETAPA 4 - ANÁLISE DE DADOS
# PARTE 1 - ANÁLISE ESTATÍSTICA DESCRITIVA
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path
from IPython.display import display

# Configurações de visualização
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.float_format", "{:,.4f}".format)

df = pd.read_csv('dados_empresa_tratado.csv')

# Configuração visual dos gráficos
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 5)
plt.rcParams["axes.titlesize"] = 14
plt.rcParams["axes.labelsize"] = 11
plt.rcParams["xtick.labelsize"] = 10
plt.rcParams["ytick.labelsize"] = 10


# ============================================================
# CARREGAMENTO DA BASE TRATADA
# ============================================================

caminho_base = Path("dados_empresa_tratado.csv")

if not caminho_base.exists():
    raise FileNotFoundError(
        "O arquivo 'dados_empresa_tratado.csv' não foi encontrado. "
        "Verifique se ele está na mesma pasta deste notebook."
    )

df = pd.read_csv(caminho_base)

# Converter coluna data para datetime
df["data"] = pd.to_datetime(df["data"], errors="coerce")

print(df.to_string())

     id_venda       data  mes  trimestre      cliente tipo_cliente  tempo_relacionamento_meses faixa_renda segmento     produto    categoria  marca linha_produto  quantidade  preco_unitario  desconto     receita  custo_unitario       lucro        regiao          cidade canal_venda     vendedor  meta_venda atingiu_meta  prazo_entrega_dias status_entrega
0           1 2024-12-14   12          4  Cliente_150         Novo                           1       Média   Varejo       Mouse  Periféricos   Beta        Padrão           5      4,697.1200    0.1800 19,258.1920      3,172.2600  3,396.8920         Norte          Manaus      Online  Vendedor_02 24,931.1100          Não                   9       Atrasado
1           2 2024-03-09    3          1  Cliente_109         Novo                           0        Alta   Varejo  Smartphone    Telefonia  Delta        Padrão          10        506.5400    0.1200  4,457.5520        307.6600  1,380.9520         Norte          Manaus      Online  Vendedor_08  5,780.2400          Não                  13       Atrasado
2           3 2024-02-14    2          1  Cliente_108         Novo                           5       Média   Varejo    Notebook  Informática  Delta     Econômico           1        470.3400    0.2300    362.1618        289.3800     72.7818      Nordeste        Salvador      Online  Vendedor_19    554.4600          Não                   8       Atrasado
3           4 2024-07-20    7          3  Cliente_141   Recorrente                          15       Baixa   Varejo     Teclado  Periféricos   Beta     Econômico           6      4,524.5200    0.2100 21,446.2248      2,723.5700  5,104.8048           Sul        Curitiba      Online  Vendedor_20 30,872.4900          Não                  10       Atrasado
4           5 2024-07-11    7          3  Cliente_150   Recorrente                          17       Média  Atacado     Monitor  Informática  Delta       Premium           8      3,178.6000    0.1700 21,105.9040      2,543.4000    758.7040           Sul    Porto Alegre        Loja  Vendedor_10 24,448.6400          Não                  14       Atrasado
5           6 2024-05-31    5          2  Cliente_127   Recorrente                          29        Alta  Atacado     Monitor  Informática   Beta       Premium           8      2,144.6400    0.1100 15,269.8368      1,309.5300  4,793.5968      Nordeste        Salvador        Loja  Vendedor_10 18,388.7900          Não                   6       No prazo
6           7 2024-01-20    1          1  Cliente_126   Recorrente                          28       Baixa  Atacado  Smartphone       Outros  Alpha       Premium           5      2,760.8300    0.1600 11,595.4860      1,770.2200  2,744.3860       Sudeste       São Paulo      Online  Vendedor_03 14,324.9500          Não                   2       No prazo
7           8 2024-05-10    5          2  Cliente_024   Recorrente                          20       Baixa  Atacado       Mouse  Periféricos  Gamma       Premium          10      5,446.0300    0.1900 44,112.8430      3,116.1100 12,951.7430  Centro-Oeste        Brasília        Loja  Vendedor_03 55,981.7100          Não                   6       No prazo
8           9 2024-12-15   12          4  Cliente_099   Recorrente                          44        Alta  Atacado    Notebook  Informática  Gamma       Premium           8      3,175.6000    0.0000 25,404.8000      2,114.8000  8,486.4000           Sul    Porto Alegre      Online  Vendedor_15 28,270.9300          Não                  13       Atrasado
9          10 2024-11-11   11          4  Cliente_197         Novo                           3       Baixa  Atacado       Mouse  Periféricos   Beta       Premium           4      4,201.2700    0.1700 13,948.2164      3,706.3100   -877.0236         Norte           Belém      Online  Vendedor_08 18,397.1200          Não                  12       Atrasado
10         11 2024-02-09    2          1  Cliente_141   Recorrente                           4       Média  Atacado     Headset  Periféricos  Delta        Padrão           9      5,221.7100    0.1100 41,825.8971      2,910.8500 15,628.2471         Norte          Manaus      Online  Vendedor_14 54,118.4800          Não                  13       Atrasado
11         12 2024-05-15    5          2  Cliente_046         Novo                           1       Baixa   Varejo     Teclado  Periféricos  Delta        Padrão           9        645.9400    0.1000  5,232.1140        529.3900    467.6040       Sudeste       São Paulo      Online  Vendedor_08  5,797.9300          Não                   6       No prazo
12         13 2024-09-09    9          3  Cliente_038   Recorrente                          23       Baixa  Atacado    Notebook  Informática  Delta       Premium           5      1,059.7700    0.1100  4,715.9765        705.7700  1,187.1265      Nordeste          Recife        Loja  Vendedor_20  5,499.1900          Não                   7       No prazo
13         14 2024-12-15   12          4  Cliente_144   Recorrente                          39        Alta  Atacado       Mouse  Periféricos   Beta       Premium           9      4,810.0900    0.0500 41,126.2695      3,363.0600 10,858.7295           Sul        Curitiba        Loja  Vendedor_13 42,444.5800          Não                   6       No prazo
14         15 2024-06-24    6          2  Cliente_054         Novo                           5       Baixa  Atacado     Headset  Periféricos  Alpha        Padrão           2      5,263.9800    0.1200  9,264.6048      3,214.3200  2,835.9648       Sudeste       São Paulo      Online  Vendedor_04 11,740.4900          Não                   6       No prazo
15         16 2024-08-13    8          3  Cliente_158         Novo                           5       Média   Varejo       Mouse  Periféricos  Alpha     Econômico           5      3,979.7900    0.0900 18,108.0445      2,100.1400  7,607.3445         Norte          Manaus      Online  Vendedor_07 20,462.3200          Não                  12       Atrasado
16         17 2024-07-18    7          3  Cliente_032   Recorrente                          22       Média   Varejo     Headset  Periféricos   Beta       Premium           9        326.1100    0.1300  2,553.4413        261.9000    196.3413  Centro-Oeste        Brasília        Loja  Vendedor_15  3,468.8000          Não                   7       No prazo
17         18 2024-10-15   10          4  Cliente_088         Novo                           5        Alta  Atacado  Impressora  Informática  Delta        Padrão           3      4,984.4400    0.0300 14,504.7204      4,369.9800  1,394.7804         Norte          Manaus        Loja  Vendedor_06 16,414.9700          Não                   2       No prazo
18         19 2024-12-18   12          4  Cliente_077         Novo                           2        Alta   Varejo    Notebook  Informática   Beta       Premium           9      3,302.0900    0.0000 29,718.8100      2,203.7000  9,885.5100  Centro-Oeste         Goiânia        Loja  Vendedor_17 31,098.6400          Não                   8       Atrasado
19         20 2024-01-02    1          1  Cliente_195         Novo                           0        Alta   Varejo       Mouse  Periféricos   Beta        Padrão           7      3,339.2100    0.1200 20,569.5336      2,367.6200  3,996.1936      Nordeste          Recife      Online  Vendedor_13 27,940.4300          Não                   2       No prazo
20         21 2024-11-10   11          4  Cliente_072         Novo                           2       Baixa  Atacado     Monitor  Informática   Beta       Premium           2      2,693.8600    0.2100  4,256.2988      2,121.9300     12.4388       Sudeste  Rio de Janeiro        Loja  Vendedor_07  5,923.7500          Não                  11       Atrasado
21         22 2024-11-06   11          4  Cliente_027         Novo                           2       Baixa   Varejo       Mouse  Periféricos  Delta       Premium           9      1,055.1200    0.0700  8,831.3544        542.5500  3,948.4044  Centro-Oeste        Brasília        Loja  Vendedor_07 10,887.3200          Não                   2       No prazo
22         23 2024-01-10    1          1  Cliente_089   Recorrente                          47        Alta   Varejo       Mouse  Periféricos   Beta        Padrão           1        456.6400    0.0100    452.0736        255.6200    196.4536           Sul        Curitiba      Online  Vendedor_13    506.4200          Não                   1       No prazo
23         24 2024-10-23   10          4  Cliente_102         Novo                           4        Alta  Atacado     Monitor  Informática  Delta     Econômico           6      2,041.6300    0.2400  9,309.8328      1,502.9200    292.3128       Sudeste  Rio de Janeiro        Loja  Vendedor_03 11,912.6800          Não                  12       Atrasado
24         25 2024-05-15    5          2  Cliente_038   Recorrente                          29        Alta  Atacado      Tablet  Informática   Beta     Econômico           2      2,093.2000    0.0300  4,060.8080      1,249.9800  1,560.8480         Norte          Manaus        Loja  Vendedor_05  4,208.0900          Não                   3       No prazo
25         26 2024-04-15    4          2  Cliente_055   Recorrente                          14       Baixa   Varejo      Tablet  Informática  Alpha     Econômico           1      5,482.9000    0.1000  4,934.6100      4,630.0900    304.5200         Norte          Manaus        Loja  Vendedor_07  5,675.4200          Não                   8       Atrasado
26         27 2024-08-18    8          3  Cliente_016   Recorrente                          32       Baixa  Atacado     Teclado  Periféricos   Beta       Premium           2      1,345.9700    0.1800  2,207.3908        847.3100    512.7708  Centro-Oeste        Brasília        Loja  Vendedor_19  2,984.8400          Não                   2       No prazo
27         28 2024-12-19   12          4  Cliente_156   Recorrente                           9       Baixa   Varejo     Headset  Periféricos   Beta       Premium           1      4,159.1000    0.1900  3,368.8710      3,033.5300    335.3410      Nordeste        Salvador      Online  Vendedor_06  4,939.2500          Não                   2       No prazo
28         29 2024-11-07   11          4  Cliente_133   Recorrente                          21        Alta  Atacado      Tablet  Informática  Delta       Premium           7      4,982.3100    0.0900 31,737.3147      2,704.1500 12,808.2647         Norte          Manaus      Online  Vendedor_18 36,108.1200          Não                   3       No prazo
29         30 2024-12-25   12          4  Cliente_116         Novo                           5        Alta   Varejo    Notebook  Informática   Beta     Econômico           9      3,050.7000    0.1000 24,710.6700      2,651.1800    850.0500  Centro-Oeste         Goiânia      Online  Vendedor_15 29,145.6200          Não                  14       Atrasado
30         31 2024-07-24    7          3  Cliente_064   Recorrente                           3        Alta  Atacado       Mouse  Periféricos   Beta       Premium           1      4,489.3600    0.1500  3,815.9560      3,943.9500   -127.9940  Centro-Oeste        Brasília      Online  Vendedor_15  4,945.9800          Não                   9       Atrasado
31         32 2024-03-14    3          1  Cliente_172   Recorrente                          45       Baixa   Varejo      Tablet  Informática  Delta     Econômico           8        948.5200    0.0700  7,056.9888        488.1700  3,151.6288       Sudeste  Rio de Janeiro        Loja  Vendedor_03  8,216.2600          Não                   7       No prazo
32         33 2024-01-16    1          1  Cliente_036         Novo                           4       Média  Atacado     Monitor  Informática  Gamma     Econômico           3      4,349.9500    0.0500 12,397.3575      2,640.5700  4,475.6475      Nordeste          Recife      Online  Vendedor_04 12,101.2600          Sim                   6       No prazo
33         34 2024-09-24    9          3  Cliente_104   Recorrente                          48        Alta  Atacado     Headset  Periféricos  Delta     Econômico           7      4,103.2100    0.1000 25,850.2230      2,789.5200  6,323.5830      Nordeste        Salvador        Loja  Vendedor_07 25,940.5600          Não                   9       Atrasado
34         35 2024-12-08   12          4  Cliente_118   Recorrente                          46        Alta  Atacado       Mouse  Periféricos  Gamma     Econômico           8      3,806.9400    0.2000 24,364.4160      2,272.0200  6,188.2560  Centro-Oeste         Goiânia      Online  Vendedor_13 34,968.5100          Não                   2       No prazo
35         36 2024-03-22    3          1  Cliente_022         Novo                           2       Baixa  Atacado       Mouse  Periféricos  Gamma       Premium           2      1,944.9800    0.1400  3,345.3656      1,002.0700  1,341.2256         Norte          Manaus        Loja  Vendedor_02  3,992.5600          Não                   9       Atrasado
36         37 2024-08-06    8          3  Cliente_138   Recorrente                          18       Baixa  Atacado      Tablet  Informática  Gamma     Econômico           9        628.5000    0.0700  5,260.5450        473.3700  1,000.2150       Sudeste  Rio de Janeiro        Loja  Vendedor_03  6,601.5100          Não                   6       No prazo
37         38 2024-06-27    6          2  Cliente_005         Novo                           4       Média   Varejo     Teclado  Periféricos  Alpha       Premium           6      1,803.3700    0.1800  8,872.5804      1,296.4300  1,094.0004      Nordeste          Recife        Loja  Vendedor_03 12,119.4500          Não                   9       Atrasado
38         39 2024-06-09    6          2  Cliente_142         Novo                           2       Média  Atacado     Monitor  Informática  Alpha        Padrão          11      3,550.4900    0.1600 32,806.5276      2,602.9300  4,174.2976         Norte           Belém        Loja  Vendedor_20 46,693.2900          Não                   7       No prazo
39         40 2024-04-12    4          2  Cliente_013         Novo                           1       Média   Varejo      Tablet  Informática  Alpha       Premium           4      2,316.3700    0.0900  8,431.5868      1,315.4000  3,169.9868      Nordeste        Salvador      Online  Vendedor_10  9,903.7900          Não                   5       No prazo
40         41 2024-12-01   12          4  Cliente_005   Recorrente                           4       Média  Atacado     Teclado  Periféricos   Beta        Padrão           9      4,174.8200    0.0400 36,070.4448      2,808.4500 10,794.3948       Sudeste       São Paulo      Online  Vendedor_01 38,583.7300          Não                   7       No prazo
41         42 2024-12-09   12          4  Cliente_169   Recorrente                           6       Baixa  Atacado    Notebook  Informática   Beta       Premium           5      3,627.0700    0.0500 17,228.5825      2,135.0900  6,553.1325       Sudeste       São Paulo        Loja  Vendedor_18 20,873.3700          Não                  11       Atrasado
42         43 2024-11-26   11          4  Cliente_181   Recorrente                           5       Baixa   Varejo     Headset  Periféricos  Gamma       Premium           6      5,592.2400    0.1700 27,849.3552      3,455.0500  7,119.0552      Nordeste        Salvador        Loja  Vendedor_12 37,560.6100          Não                   9       Atrasado
43         44 2024-11-26   11          4  Cliente_015   Recorrente                           9       Baixa   Varejo    Notebook  Informática   Beta     Econômico           8        628.0800    0.0400  4,823.6544        340.6900  2,098.1344         Norte           Belém        Loja  Vendedor_17  4,601.7000          Sim                   1       No prazo
44         45 2024-02-01    2          1  Cliente_041   Recorrente                          49       Baixa  Atacado     Teclado  Periféricos   Beta       Premium           5      5,694.7000    0.1300 24,771.9450      3,055.3000  9,495.4450  Centro-Oeste         Goiânia        Loja  Vendedor_01 27,460.8800          Não                  11       Atrasado
45         46 2024-01-01    1          1  Cliente_080         Novo                           0       Baixa   Varejo     Teclado  Periféricos  Gamma        Padrão           7      5,633.7600    0.0000 39,436.3200      3,875.3800 12,308.6600           Sul    Porto Alegre        Loja  Vendedor_06 45,588.4700          Não                   8       Atrasado
46         47 2024-12-10   12          4  Cliente_168   Recorrente                          23        Alta   Varejo    Notebook  Informática  Gamma        Padrão           7      5,823.3300    0.1100 36,279.3459      4,114.4400  7,478.2659         Norte           Belém      Online  Vendedor_17 47,314.6900          Não                   4       No prazo
47         48 2024-04-03    4          2  Cliente_011   Recorrente                          40        Alta  Atacado    Notebook  Informática  Alpha        Padrão           9      5,355.8900    0.1200 42,418.6488      2,969.0300 15,697.3788         Norte          Manaus      Online  Vendedor_10 50,100.0000          Não                  11       Atrasado
48         49 2024-04-28    4          2  Cliente_185   Recorrente                          57       Média  Atacado     Teclado  Periféricos   Beta     Econômico          11      2,455.4400    0.0100 26,739.7416      1,482.6600 10,430.4816           Sul        Curitiba      Online  Vendedor_10 29,838.1800          Não                   4       No prazo
49         50 2024-10-31   10          4  Cliente_193         Novo                           0        Alta   Varejo      Tablet       Outros  Alpha       Premium           1      3,220.2800    0.0300  3,123.6716      2,491.5200    632.1516           Sul    Porto Alegre      Online  Vendedor_03  3,077.6600          Sim                  12       Atrasado
50         51 2024-11-17   11          4  Cliente_143   Recorrente                          22       Média   Varejo    Notebook  Informática  Alpha     Econômico           1        387.5800    0.0000    387.5800        321.9900     65.5900  Centro-Oeste         Goiânia      Online  Vendedor_18    368.0900          Sim                   2       No prazo
51         52 2024-06-14    6          2  Cliente_129         Novo                           1        Alta   Varejo     Monitor  Informática  Delta        Padrão          10      5,720.2900    0.1600 48,050.4360      3,972.7000  8,323.4360         Norte           Belém      Online  Vendedor_16 53,369.0700          Não                  14       Atrasado
52         53 2024-06-12    6          2  Cliente_167         Novo                           1        Alta  Atacado     Teclado  Periféricos  Alpha        Padrão           7      5,490.4100    0.1400 33,052.2682      3,086.5300 11,446.5582      Nordeste        Salvador        Loja  Vendedor_13 43,129.1400          Não                   1       No prazo
53         54 2024-09-15    9          3  Cliente_154         Novo                           2       Baixa   Varejo  Smartphone    Telefonia  Delta       Premium           1      3,114.2800    0.1800  2,553.7096      2,544.7600      8.9496  Centro-Oeste         Goiânia        Loja  Vendedor_09  3,197.2800          Não                  14       Atrasado
54         55 2024-12-14   12          4  Cliente_173   Recorrente                          58       Média   Varejo     Teclado  Periféricos   Beta     Econômico          10      1,032.0900    0.2000  8,256.7200        819.0800     65.9200       Sudeste       São Paulo      Online  Vendedor_16 10,081.9000          Não                   2       No prazo

In [2]:
# VALIDAÇÃO INICIAL DA BASE
# ============================================================

print(f"Quantidade de linhas: {df.shape[0]}")
print(f"Quantidade de colunas: {df.shape[1]}")
print(f"Total de valores nulos: {df.isna().sum().sum()}")
print(f"Total de linhas duplicadas: {df.duplicated().sum()}")

df.info()

Quantidade de linhas: 1000
Quantidade de colunas: 27
Total de valores nulos: 0
Total de linhas duplicadas: 0
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_venda                    1000 non-null   int64
 1   data                        1000 non-null   datetime64[us]
 2   mes                         1000 non-null   int64
 3   trimestre                   1000 non-null   int64
 4   cliente                     1000 non-null   str
 5   tipo_cliente                1000 non-null   str
 6   tempo_relacionamento_meses  1000 non-null   int64
 7   faixa_renda                 1000 non-null   str
 8   segmento                    1000 non-null   str
 9   produto                     1000 non-null   str
 10  categoria                   1000 non-null   str
 11  marca                       1000 non-null   str
 12  linha_produto               1000 non-null   str
 13  quantidade                  1000 non-null   int64
 14  preco_unitario              1000 non-null   float64
 15  desconto                    1000 non-null   float64
 16  receita                     1000 non-null   float64
 17  custo_unitario              1000 non-null   float64
 18  lucro                       1000 non-null   float64
 19  regiao                      1000 non-null   str
 20  cidade                      1000 non-null   str
 21  canal_venda                 1000 non-null   str
 22  vendedor                    1000 non-null   str
 23  meta_venda                  1000 non-null   float64
 24  atingiu_meta                1000 non-null   str
 25  prazo_entrega_dias          1000 non-null   int64
 26  status_entrega              1000 non-null   str
dtypes: datetime64[us](1), float64(6), int64(6), str(14)
memory usage: 211.1 KB

In [3]:
# 4.1 - KPIs GERAIS
# ============================================================

receita_total = df["receita"].sum()
lucro_total = df["lucro"].sum()
margem_lucro = lucro_total / receita_total
quantidade_total = df["quantidade"].sum()
ticket_medio = df["receita"].mean()
desconto_medio = df["desconto"].mean()
meta_total = df["meta_venda"].sum()
taxa_atingimento_meta = (df["atingiu_meta"] == "Sim").mean()
taxa_atraso = (df["status_entrega"] == "Atrasado").mean()
total_vendas = df["id_venda"].count()

kpis_gerais = pd.DataFrame({
    "KPI": [
        "Total de Vendas",
        "Receita Total",
        "Lucro Total",
        "Margem de Lucro",
        "Quantidade Vendida",
        "Ticket Médio por Venda",
        "Desconto Médio",
        "Meta Total",
        "Taxa de Atingimento de Meta",
        "Taxa de Entregas Atrasadas"
    ],
    "Valor": [
        total_vendas,
        receita_total,
        lucro_total,
        margem_lucro,
        quantidade_total,
        ticket_medio,
        desconto_medio,
        meta_total,
        taxa_atingimento_meta,
        taxa_atraso
    ]
})

kpis_gerais

                           KPI           Valor
0              Total de Vendas      1,000.0000
1                Receita Total 15,196,118.4787
2                  Lucro Total  3,081,804.6787
3              Margem de Lucro          0.2028
4           Quantidade Vendida      6,062.0000
5       Ticket Médio por Venda     15,196.1185
6               Desconto Médio          0.1282
7                   Meta Total 18,353,644.5200
8  Taxa de Atingimento de Meta          0.0700
9   Taxa de Entregas Atrasadas          0.5190

In [4]:
# SEPARAÇÃO DOS ATRIBUTOS POR TIPO
# ============================================================

atributos_id_temporais = [
    "id_venda",
    "data",
    "mes",
    "trimestre"
]

atributos_qualitativos = [
    "cliente",
    "tipo_cliente",
    "faixa_renda",
    "segmento",
    "produto",
    "categoria",
    "marca",
    "linha_produto",
    "regiao",
    "cidade",
    "canal_venda",
    "vendedor",
    "atingiu_meta",
    "status_entrega"
]

atributos_quantitativos = [
    "tempo_relacionamento_meses",
    "quantidade",
    "preco_unitario",
    "desconto",
    "receita",
    "custo_unitario",
    "lucro",
    "meta_venda",
    "prazo_entrega_dias"
]

print("Atributos de identificação/temporais:")
print(atributos_id_temporais)

print("\nAtributos qualitativos:")
print(atributos_qualitativos)

print("\nAtributos quantitativos:")
print(atributos_quantitativos)

Atributos de identificação/temporais:
['id_venda', 'data', 'mes', 'trimestre']

Atributos qualitativos:
['cliente', 'tipo_cliente', 'faixa_renda', 'segmento', 'produto', 'categoria', 'marca', 'linha_produto', 'regiao', 'cidade', 'canal_venda', 'vendedor', 'atingiu_meta', 'status_entrega']

Atributos quantitativos:
['tempo_relacionamento_meses', 'quantidade', 'preco_unitario', 'desconto', 'receita', 'custo_unitario', 'lucro', 'meta_venda', 'prazo_entrega_dias']

# Análise descritiva dos dados qualitativos (nominais / ordinais)
segue abaixo

In [5]:
# RESUMO DOS ATRIBUTOS QUALITATIVOS
# ============================================================

resumo_qualitativo = []

for coluna in atributos_qualitativos:
    frequencias = df[coluna].value_counts(dropna=False)

    moda = frequencias.index[0]
    freq_abs_moda = frequencias.iloc[0]
    freq_rel_moda = freq_abs_moda / len(df)

    resumo_qualitativo.append({
        "atributo": coluna,
        "valores_unicos": df[coluna].nunique(dropna=True),
        "moda": moda,
        "frequencia_absoluta_moda": freq_abs_moda,
        "frequencia_relativa_moda": freq_rel_moda,
        "frequencia_relativa_moda_%": round(freq_rel_moda * 100, 2)
    })

resumo_qualitativo = pd.DataFrame(resumo_qualitativo)

resumo_qualitativo

,atributo,valores_unicos,moda,frequencia_absoluta_moda,frequencia_relativa_moda,frequencia_relativa_moda_%
0,cliente,199,Cliente_141,12,0.0120,1.2000
1,tipo_cliente,2,Recorrente,519,0.5190,51.9000
2,faixa_renda,3,Baixa,389,0.3890,38.9000
3,segmento,2,Atacado,508,0.5080,50.8000
4,produto,8,Monitor,143,0.1430,14.3000
5,categoria,4,Informática,492,0.4920,49.2000
6,marca,4,Alpha,255,0.2550,25.5000
7,linha_produto,3,Econômico,347,0.3470,34.7000
8,regiao,5,Norte,209,0.2090,20.9000
9,cidade,10,Manaus,116,0.1160,11.6000
10,canal_venda,2,Online,522,0.5220,52.2000
11,vendedor,20,Vendedor_10,63,0.0630,6.3000
12,atingiu_meta,2,Não,930,0.9300,93.0000
13,status_entrega,2,Atrasado,519,0.5190,51.9000

In [6]:
# FUNÇÃO PARA TABELA DE FREQUÊNCIA QUALITATIVA
# ============================================================

def tabela_frequencia_qualitativa(base, coluna):
    """
    Gera a tabela de frequência de uma variável qualitativa.
    """
    # O parâmetro 'normalize=True' já calcula a frequência relativa
    tabela = base[coluna].value_counts(dropna=False, normalize=True).reset_index()
    tabela.columns = [coluna, "frequencia_relativa"]

    # Calcula a frequência absoluta a partir da relativa
    tabela["frequencia_absoluta"] = (tabela["frequencia_relativa"] * len(base)).astype(int)

    # Converte para porcentagem
    tabela["frequencia_relativa_%"] = (tabela["frequencia_relativa"] * 100).round(2)

    # Calcula a frequência acumulada
    tabela["frequencia_acumulada_%"] = (tabela["frequencia_relativa"].cumsum() * 100).round(2)

    # Reordena as colunas para um layout mais lógico
    return tabela[[coluna, "frequencia_absoluta", "frequencia_relativa_%", "frequencia_acumulada_%"]]   

# ============================================================
# TABELAS DE FREQUÊNCIA PARA TODOS OS ATRIBUTOS QUALITATIVOS
# ============================================================

for coluna in atributos_qualitativos:
    print(f"\n{'='*80}")
    print(f"Tabela de frequência do atributo: {coluna}")
    print(f"{'='*80}")

    tabela_freq = tabela_frequencia_qualitativa(df, coluna)

    # Remove a condição e exibe a tabela completa com um contexto temporário
    with pd.option_context('display.max_rows', None):
        display(tabela_freq)

================================================================================
Tabela de frequência do atributo: cliente
================================================================================

,cliente,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Cliente_141,12,1.2000,1.2000
1,Cliente_027,10,1.0000,2.2000
2,Cliente_109,9,0.9000,3.1000
3,Cliente_024,9,0.9000,4.0000
4,Cliente_016,9,0.9000,4.9000
5,Cliente_036,9,0.9000,5.8000
6,Cliente_115,9,0.9000,6.7000
7,Cliente_048,9,0.9000,7.6000
8,Cliente_188,9,0.9000,8.5000
9,Cliente_121,9,0.9000,9.4000
10,Cliente_144,8,0.8000,10.2000
11,Cliente_138,8,0.8000,11.0000
12,Cliente_005,8,0.8000,11.8000
13,Cliente_129,8,0.8000,12.6000
14,Cliente_154,8,0.8000,13.4000
15,Cliente_052,8,0.8000,14.2000
16,Cliente_163,8,0.8000,15.0000
17,Cliente_120,8,0.8000,15.8000
18,Cliente_033,8,0.8000,16.6000
19,Cliente_092,8,0.8000,17.4000
20,Cliente_087,8,0.8000,18.2000
21,Cliente_057,8,0.8000,19.0000
22,Cliente_035,8,0.8000,19.8000
23,Cliente_175,8,0.8000,20.6000
24,Cliente_150,7,0.7000,21.3000
25,Cliente_127,7,0.7000,22.0000
26,Cliente_133,7,0.7000,22.7000
27,Cliente_064,7,0.7000,23.4000
28,Cliente_104,7,0.7000,24.1000
29,Cliente_041,7,0.7000,24.8000
30,Cliente_080,7,0.7000,25.5000
31,Cliente_168,7,0.7000,26.2000
32,Cliente_011,7,0.7000,26.9000
33,Cliente_128,7,0.7000,27.6000
34,Cliente_060,7,0.7000,28.3000
35,Cliente_090,7,0.7000,29.0000
36,Cliente_071,7,0.7000,29.7000
37,Cliente_043,7,0.7000,30.4000
38,Cliente_149,7,0.7000,31.1000
39,Cliente_040,7,0.7000,31.8000
40,Cliente_160,7,0.7000,32.5000
41,Cliente_095,7,0.7000,33.2000
42,Cliente_176,7,0.7000,33.9000
43,Cliente_062,7,0.7000,34.6000
44,Cliente_151,7,0.7000,35.3000
45,Cliente_123,7,0.7000,36.0000
46,Cliente_139,7,0.7000,36.7000
47,Cliente_126,6,0.6000,37.3000
48,Cliente_099,6,0.6000,37.9000
49,Cliente_197,6,0.6000,38.5000
50,Cliente_046,6,0.6000,39.1000
51,Cliente_032,6,0.6000,39.7000
52,Cliente_195,6,0.6000,40.3000
53,Cliente_089,6,0.6000,40.9000
54,Cliente_118,6,0.6000,41.5000
55,Cliente_022,6,0.6000,42.1000
56,Cliente_013,6,0.6000,42.7000
57,Cliente_185,6,0.6000,43.3000
58,Cliente_143,6,0.6000,43.9000
59,Cliente_167,6,0.6000,44.5000
60,Cliente_173,6,0.6000,45.1000
61,Cliente_001,6,0.6000,45.7000
62,Cliente_017,6,0.6000,46.3000
63,Cliente_014,6,0.6000,46.9000
64,Cliente_045,6,0.6000,47.5000
65,Cliente_106,6,0.6000,48.1000
66,Cliente_066,6,0.6000,48.7000
67,Cliente_182,6,0.6000,49.3000
68,Cliente_049,6,0.6000,49.9000
69,Cliente_119,6,0.6000,50.5000
70,Cliente_053,6,0.6000,51.1000
71,Cliente_117,6,0.6000,51.7000
72,Cliente_179,6,0.6000,52.3000
73,Cliente_178,6,0.6000,52.9000
74,Cliente_110,6,0.6000,53.5000
75,Cliente_093,6,0.6000,54.1000
76,Cliente_065,6,0.6000,54.7000
77,Cliente_051,6,0.6000,55.3000
78,Cliente_140,6,0.6000,55.9000
79,Cliente_019,6,0.6000,56.5000
80,Cliente_081,6,0.6000,57.1000
81,Cliente_147,6,0.6000,57.7000
82,Cliente_196,6,0.6000,58.3000
83,Cliente_098,6,0.6000,58.9000
84,Cliente_018,6,0.6000,59.5000
85,Cliente_088,5,0.5000,60.0000
86,Cliente_077,5,0.5000,60.5000
87,Cliente_172,5,0.5000,61.0000
88,Cliente_142,5,0.5000,61.5000
89,Cliente_169,5,0.5000,62.0000
90,Cliente_155,5,0.5000,62.5000
91,Cliente_148,5,0.5000,63.0000
92,Cliente_067,5,0.5000,63.5000
93,Cliente_034,5,0.5000,64.0000
94,Cliente_028,5,0.5000,64.5000
95,Cliente_084,5,0.5000,65.0000
96,Cliente_192,5,0.5000,65.5000
97,Cliente_009,5,0.5000,66.0000
98,Cliente_083,5,0.5000,66.5000
99,Cliente_091,5,0.5000,67.0000
100,Cliente_174,5,0.5000,67.5000
101,Cliente_020,5,0.5000,68.0000
102,Cliente_189,5,0.5000,68.5000
103,Cliente_112,5,0.5000,69.0000
104,Cliente_096,5,0.5000,69.5000
105,Cliente_029,5,0.5000,70.0000
106,Cliente_132,5,0.5000,70.5000
107,Cliente_012,5,0.5000,71.0000
108,Cliente_136,5,0.5000,71.5000
109,Cliente_183,5,0.5000,72.0000
110,Cliente_170,5,0.5000,72.5000
111,Cliente_158,4,0.4000,72.9000
112,Cliente_102,4,0.4000,73.3000
113,Cliente_156,4,0.4000,73.7000
114,Cliente_116,4,0.4000,74.1000
115,Cliente_181,4,0.4000,74.5000
116,Cliente_193,4,0.4000,74.9000
117,Cliente_008,4,0.4000,75.3000
118,Cliente_061,4,0.4000,75.7000
119,Cliente_171,4,0.4000,76.1000
120,Cliente_031,4,0.4000,76.5000
121,Cliente_002,4,0.4000,76.9000
122,Cliente_194,4,0.4000,77.3000
123,Cliente_068,4,0.4000,77.7000
124,Cliente_114,4,0.4000,78.1000
125,Cliente_003,4,0.4000,78.5000
126,Cliente_137,4,0.4000,78.9000
127,Cliente_134,4,0.4000,79.3000
128,Cliente_023,4,0.4000,79.7000
129,Cliente_165,4,0.4000,80.1000
130,Cliente_037,4,0.4000,80.5000
131,Cliente_103,4,0.4000,80.9000
132,Cliente_086,4,0.4000,81.3000
133,Cliente_075,4,0.4000,81.7000
134,Cliente_162,4,0.4000,82.1000
135,Cliente_124,4,0.4000,82.5000
136,Cliente_042,4,0.4000,82.9000
137,Cliente_047,4,0.4000,83.3000
138,Cliente_190,4,0.4000,83.7000
139,Cliente_113,4,0.4000,84.1000
140,Cliente_085,4,0.4000,84.5000
141,Cliente_107,4,0.4000,84.9000
142,Cliente_050,4,0.4000,85.3000
143,Cliente_070,4,0.4000,85.7000
144,Cliente_186,4,0.4000,86.1000
145,Cliente_025,4,0.4000,86.5000
146,Cliente_164,4,0.4000,86.9000
147,Cliente_021,4,0.4000,87.3000
148,Cliente_111,4,0.4000,87.7000
149,Cliente_146,4,0.4000,88.1000
150,Cliente_125,4,0.4000,88.5000
151,Cliente_130,4,0.4000,88.9000
152,Cliente_108,3,0.3000,89.2000
153,Cliente_038,3,0.3000,89.5000
154,Cliente_054,3,0.3000,89.8000
155,Cliente_055,3,0.3000,90.1000
156,Cliente_101,3,0.3000,90.4000
157,Cliente_058,3,0.3000,90.7000
158,Cliente_094,3,0.3000,91.0000
159,Cliente_184,3,0.3000,91.3000
160,Cliente_198,3,0.3000,91.6000
161,Cliente_004,3,0.3000,91.9000
162,Cliente_082,3,0.3000,92.2000
163,Cliente_135,3,0.3000,92.5000
164,Cliente_199,3,0.3000,92.8000
165,Cliente_078,3,0.3000,93.1000
166,Cliente_069,3,0.3000,93.4000
167,Cliente_180,3,0.3000,93.7000
168,Cliente_074,3,0.3000,94.0000
169,Cliente_030,3,0.3000,94.3000
170,Cliente_063,3,0.3000,94.6000
171,Cliente_159,3,0.3000,94.9000
172,Cliente_007,3,0.3000,95.2000
173,Cliente_056,3,0.3000,95.5000
174,Cliente_122,3,0.3000,95.8000
175,Cliente_131,3,0.3000,96.1000
176,Cliente_079,3,0.3000,96.4000
177,Cliente_006,2,0.2000,96.6000
178,Cliente_152,2,0.2000,96.8000
179,Cliente_097,2,0.2000,97.0000
180,Cliente_026,2,0.2000,97.2000
181,Cliente_100,2,0.2000,97.4000
182,Cliente_161,2,0.2000,97.6000
183,Cliente_145,2,0.2000,97.8000
184,Cliente_166,2,0.2000,98.0000
185,Cliente_153,2,0.2000,98.2000
186,Cliente_187,2,0.2000,98.4000
187,Cliente_105,2,0.2000,98.6000
188,Cliente_010,2,0.2000,98.8000
189,Cliente_059,2,0.2000,99.0000
190,Cliente_039,2,0.2000,99.2000
191,Cliente_072,1,0.1000,99.3000
192,Cliente_015,1,0.1000,99.4000
193,Cliente_073,1,0.1000,99.5000
194,Cliente_191,1,0.1000,99.6000
195,Cliente_076,1,0.1000,99.7000
196,Cliente_200,1,0.1000,99.8000
197,Cliente_177,1,0.1000,99.9000
198,Cliente_157,1,0.1000,100.0000

================================================================================
Tabela de frequência do atributo: tipo_cliente
================================================================================

,tipo_cliente,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Recorrente,519,51.9000,51.9000
1,Novo,481,48.1000,100.0000

================================================================================
Tabela de frequência do atributo: faixa_renda
================================================================================

,faixa_renda,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Baixa,389,38.9000,38.9000
1,Média,310,31.0000,69.9000
2,Alta,301,30.1000,100.0000

================================================================================
Tabela de frequência do atributo: segmento
================================================================================

  segmento  frequencia_absoluta  frequencia_relativa_%  frequencia_acumulada_%
0  Atacado                  508                50.8000                 50.8000
1   Varejo                  492                49.2000                100.0000

================================================================================
Tabela de frequência do atributo: produto
================================================================================

,produto,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Monitor,143,14.3000,14.3000
1,Mouse,133,13.3000,27.6000
2,Smartphone,133,13.3000,40.9000
3,Tablet,128,12.8000,53.7000
4,Notebook,122,12.2000,65.9000
5,Teclado,115,11.5000,77.4000
6,Impressora,115,11.5000,88.9000
7,Headset,111,11.1000,100.0000

================================================================================
Tabela de frequência do atributo: categoria
================================================================================

,categoria,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Informática,492,49.2000,49.2000
1,Periféricos,346,34.6000,83.8000
2,Telefonia,132,13.2000,97.0000
3,Outros,30,3.0000,100.0000

================================================================================
Tabela de frequência do atributo: marca
================================================================================

   marca  frequencia_absoluta  frequencia_relativa_%  frequencia_acumulada_%
0  Alpha                  255                25.5000                 25.5000
1  Gamma                  252                25.2000                 50.7000
2   Beta                  250                25.0000                 75.7000
3  Delta                  243                24.3000                100.0000

================================================================================
Tabela de frequência do atributo: linha_produto
================================================================================

,linha_produto,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Econômico,347,34.7000,34.7000
1,Premium,330,33.0000,67.7000
2,Padrão,323,32.3000,100.0000

================================================================================
Tabela de frequência do atributo: regiao
================================================================================

,regiao,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Norte,209,20.9000,20.9000
1,Sul,209,20.9000,41.8000
2,Centro-Oeste,202,20.2000,62.0000
3,Sudeste,199,19.9000,81.9000
4,Nordeste,181,18.1000,100.0000

================================================================================
Tabela de frequência do atributo: cidade
================================================================================

,cidade,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Manaus,116,11.6000,11.6000
1,Curitiba,110,11.0000,22.6000
2,Goiânia,106,10.6000,33.2000
3,Rio de Janeiro,100,10.0000,43.2000
4,Porto Alegre,99,9.9000,53.1000
5,São Paulo,99,9.9000,63.0000
6,Brasília,96,9.6000,72.6000
7,Belém,93,9.3000,81.9000
8,Recife,93,9.3000,91.2000
9,Salvador,88,8.8000,100.0000

================================================================================
Tabela de frequência do atributo: canal_venda
================================================================================

,canal_venda,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Online,522,52.2000,52.2000
1,Loja,478,47.8000,100.0000

================================================================================
Tabela de frequência do atributo: vendedor
================================================================================

,vendedor,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Vendedor_10,63,6.3000,6.3000
1,Vendedor_13,60,6.0000,12.3000
2,Vendedor_12,60,6.0000,18.3000
3,Vendedor_04,55,5.5000,23.8000
4,Vendedor_18,53,5.3000,29.1000
5,Vendedor_19,50,5.0000,34.1000
6,Vendedor_03,50,5.0000,39.1000
7,Vendedor_06,50,5.0000,44.1000
8,Vendedor_17,50,5.0000,49.1000
9,Vendedor_20,49,4.9000,54.0000
10,Vendedor_05,49,4.9000,58.9000
11,Vendedor_02,48,4.8000,63.7000
12,Vendedor_07,48,4.8000,68.5000
13,Vendedor_11,48,4.8000,73.3000
14,Vendedor_15,47,4.7000,78.0000
15,Vendedor_08,46,4.6000,82.6000
16,Vendedor_09,46,4.6000,87.2000
17,Vendedor_01,44,4.4000,91.6000
18,Vendedor_16,43,4.3000,95.9000
19,Vendedor_14,41,4.1000,100.0000

================================================================================
Tabela de frequência do atributo: atingiu_meta
================================================================================

,atingiu_meta,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Não,930,93.0000,93.0000
1,Sim,70,7.0000,100.0000

================================================================================
Tabela de frequência do atributo: status_entrega
================================================================================

,status_entrega,frequencia_absoluta,frequencia_relativa_%,frequencia_acumulada_%
0,Atrasado,519,51.9000,51.9000
1,No prazo,481,48.1000,100.0000

### Análise dos Atributos Qualitativos

Os atributos qualitativos foram analisados por meio da contagem de valores únicos, frequência absoluta, frequência relativa e moda. Esse tipo de análise foram escolhidas pois permite compreender a distribuição das categorias dentro da base.

A contagem de valores únicos permitiu identificar variáveis com baixa cardinalidade, como `tipo_cliente`, `segmento`, `canal_venda`, `atingiu_meta` e `status_entrega`, e variáveis com maior cardinalidade, como `cliente` e `vendedor`.

A frequência absoluta mostrou quantas vezes cada categoria aparece na base.  
A frequência relativa indicou a participação percentual de cada categoria em relação ao total de registros. 

A moda foi utilizada para identificar a categoria mais recorrente em cada atributo.

# Análise de Dados Quantitativos
segue abaixo

In [8]:
# RESUMO DOS ATRIBUTOS QUANTITATIVOS
# ============================================================

resumo_quantitativo = []

for coluna in atributos_quantitativos:
    serie = df[coluna].dropna()

    moda = serie.mode()
    moda_valor = moda.iloc[0] if not moda.empty else np.nan

    resumo_quantitativo.append({
        "atributo": coluna,
        "contagem": serie.count(),
        "media": serie.mean(),
        "mediana": serie.median(),
        "moda": moda_valor,
        "minimo": serie.min(),
        "maximo": serie.max(),
        "amplitude": serie.max() - serie.min(),
        "desvio_padrao": serie.std(),
        "coeficiente_variacao": serie.std() / serie.mean() if serie.mean() != 0 else np.nan,
        "q1_25%": serie.quantile(0.25),
        "q2_50%": serie.quantile(0.50),
        "q3_75%": serie.quantile(0.75),
        "iqr": serie.quantile(0.75) - serie.quantile(0.25),
        "p5": serie.quantile(0.05),
        "p10": serie.quantile(0.10),
        "p90": serie.quantile(0.90),
        "p95": serie.quantile(0.95),
        "assimetria": serie.skew(),
        "curtose": serie.kurt()
    })


resumo_quantitativo = pd.DataFrame(resumo_quantitativo)

resumo_quantitativo

,atributo,contagem,media,mediana,moda,minimo,maximo,amplitude,desvio_padrao,coeficiente_variacao,q1_25%,q2_50%,q3_75%,iqr,p5,p10,p90,p95,assimetria,curtose
0,tempo_relacionamento_meses,1000,16.6660,5.0000,4.0000,0.0000,59.0000,59.0000,18.4595,1.1076,2.0000,5.0000,31.0000,29.0000,0.0000,1.0000,48.0000,53.0000,0.9009,-0.6850
1,quantidade,1000,6.0620,6.0000,7.0000,1.0000,11.0000,10.0000,3.1247,0.5155,3.0000,6.0000,9.0000,6.0000,1.0000,1.9000,10.0000,11.0000,-0.1075,-1.1669
2,preco_unitario,1000,"2,924.7153","2,780.8900","2,635.2600",81.4500,"6,738.4862","6,657.0362","1,726.8995",0.5905,"1,426.8100","2,780.8900","4,452.7450","3,025.9350",370.7425,645.1410,"5,393.0100","5,695.5800",0.1295,-1.2072
3,desconto,1000,0.1282,0.1300,0.1400,0.0000,0.2500,0.2500,0.0709,0.5534,0.0700,0.1300,0.1900,0.1200,0.0100,0.0300,0.2200,0.2400,-0.0999,-1.1326
4,receita,1000,"15,196.1185","11,199.2130",61.9020,61.9020,"64,052.0100","63,990.1080","12,773.9807",0.8406,"4,691.6275","11,199.2130","22,755.0274","18,063.3999","1,194.3333","2,092.4175","33,642.1061","42,041.8524",1.0452,0.4574
5,custo_unitario,1000,"2,034.8856","1,906.1200","1,308.2800",46.0600,"5,178.2000","5,132.1400","1,260.5210",0.6195,993.7825,"1,906.1200","3,038.5350","2,044.7525",255.9715,437.8890,"3,828.4890","4,150.0580",0.3284,-0.8906
6,lucro,1000,"3,081.8047","1,723.8235","-5,323.1080","-5,323.1080","22,781.8305","28,104.9385","4,065.4309",1.3192,437.4554,"1,723.8235","4,272.8677","3,835.4123",-556.5281,-54.5443,"8,432.4803","12,143.4831",1.8151,3.8263
7,meta_venda,1000,"18,353.6445","13,514.7750",87.4400,87.4400,"72,103.3700","72,015.9300","15,371.4257",0.8375,"5,614.7850","13,514.7750","27,480.4675","21,865.6825","1,423.3435","2,500.8380","41,139.8210","50,262.7150",1.0023,0.2899
8,prazo_entrega_dias,1000,7.6580,8.0000,14.0000,1.0000,14.0000,13.0000,4.1685,0.5443,4.0000,8.0000,11.0000,7.0000,1.0000,2.0000,13.0000,14.0000,-0.0519,-1.2613

In [9]:
# CLASSIFICAÇÃO DE ASSIMETRIA E CURTOSE
# ============================================================

def classificar_assimetria(valor):
    if valor > 1:
        return "Assimetria positiva forte"
    elif valor > 0.5:
        return "Assimetria positiva moderada"
    elif valor < -1:
        return "Assimetria negativa forte"
    elif valor < -0.5:
        return "Assimetria negativa moderada"
    else:
        return "Aproximadamente simétrica"


def classificar_curtose(valor):
    if valor > 1:
        return "Curtose elevada / caudas pesadas"
    elif valor < -1:
        return "Curtose baixa / distribuição achatada"
    else:
        return "Curtose próxima do padrão"


resumo_quantitativo["interpretacao_assimetria"] = resumo_quantitativo["assimetria"].apply(classificar_assimetria)
resumo_quantitativo["interpretacao_curtose"] = resumo_quantitativo["curtose"].apply(classificar_curtose)

resumo_quantitativo[
    [
        "atributo",
        "assimetria",
        "interpretacao_assimetria",
        "curtose",
        "interpretacao_curtose"
    ]
]

,atributo,assimetria,interpretacao_assimetria,curtose,interpretacao_curtose
0,tempo_relacionamento_meses,0.9009,Assimetria positiva moderada,-0.6850,Curtose próxima do padrão
1,quantidade,-0.1075,Aproximadamente simétrica,-1.1669,Curtose baixa / distribuição achatada
2,preco_unitario,0.1295,Aproximadamente simétrica,-1.2072,Curtose baixa / distribuição achatada
3,desconto,-0.0999,Aproximadamente simétrica,-1.1326,Curtose baixa / distribuição achatada
4,receita,1.0452,Assimetria positiva forte,0.4574,Curtose próxima do padrão
5,custo_unitario,0.3284,Aproximadamente simétrica,-0.8906,Curtose próxima do padrão
6,lucro,1.8151,Assimetria positiva forte,3.8263,Curtose elevada / caudas pesadas
7,meta_venda,1.0023,Assimetria positiva forte,0.2899,Curtose próxima do padrão
8,prazo_entrega_dias,-0.0519,Aproximadamente simétrica,-1.2613,Curtose baixa / distribuição achatada

In [10]:
# PERCENTIS DETALHADOS
# ============================================================

percentis = [0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]

tabela_percentis = df[atributos_quantitativos].quantile(percentis).T

tabela_percentis.columns = [
    "p1",
    "p5",
    "p10",
    "p25",
    "p50",
    "p75",
    "p90",
    "p95",
    "p99"
]

tabela_percentis

,p1,p5,p10,p25,p50,p75,p90,p95,p99
tempo_relacionamento_meses,0.0000,0.0000,1.0000,2.0000,5.0000,31.0000,48.0000,53.0000,58.0000
quantidade,1.0000,1.0000,1.9000,3.0000,6.0000,9.0000,10.0000,11.0000,11.0000
preco_unitario,105.9441,370.7425,645.1410,"1,426.8100","2,780.8900","4,452.7450","5,393.0100","5,695.5800","5,932.5374"
desconto,0.0000,0.0100,0.0300,0.0700,0.1300,0.1900,0.2200,0.2400,0.2500
receita,361.8968,"1,194.3333","2,092.4175","4,691.6275","11,199.2130","22,755.0274","33,642.1061","42,041.8524","50,751.8328"
custo_unitario,72.6313,255.9715,437.8890,993.7825,"1,906.1200","3,038.5350","3,828.4890","4,150.0580","4,850.9862"
lucro,"-2,631.7259",-556.5281,-54.5443,437.4554,"1,723.8235","4,272.8677","8,432.4803","12,143.4831","17,968.3113"
meta_venda,367.7592,"1,423.3435","2,500.8380","5,614.7850","13,514.7750","27,480.4675","41,139.8210","50,262.7150","61,696.8640"
prazo_entrega_dias,1.0000,1.0000,2.0000,4.0000,8.0000,11.0000,13.0000,14.0000,14.0000

### Análise dos Atributos Quantitativos

Os atributos quantitativos foram analisados por meio de medidas de tendência central, posição, dispersão e formato da distribuição. Foram calculadas média, mediana, moda, mínimo, máximo, amplitude, desvio padrão, coeficiente de variação, quartis, percentis, assimetria e curtose.

A média foi utilizada para representar o valor médio das variáveis  
A mediana foi analisada como medida de posição central menos sensível a valores extremos.  
A moda foi calculada para identificar o valor mais frequente em cada atributo, sendo especialmente útil em variáveis discretas, como quantidade vendida e prazo de entrega.

Os quartis e percentis permitiram compreender a distribuição dos dados em diferentes pontos, identificando faixas inferiores, centrais e superiores.  
O intervalo interquartil foi utilizado para observar a dispersão da parte central da distribuição.  

A assimetria foi utilizada para avaliar se as distribuições são aproximadamente simétricas ou se possuem concentração em um dos lados. Já a curtose foi analisada para verificar a presença de caudas mais pesadas ou distribuições mais achatadas.

Além disso, foram gerados histogramas e boxplots para visualizar a distribuição dos atributos quantitativos. A matriz de correlação foi utilizada para identificar relações lineares entre variáveis numéricas, especialmente entre receita, lucro, desconto, quantidade, preço unitário e meta de venda.

# Atributos de Identificação e Temporais
id_venda

data, mes, trimestre

In [13]:
# VALIDAÇÃO DE IDENTIFICADOR DA VENDA
# ============================================================

total_linhas = df.shape[0]
ids_unicos = df["id_venda"].nunique()
ids_duplicados = df["id_venda"].duplicated().sum()
id_minimo = df["id_venda"].min()
id_maximo = df["id_venda"].max()

validacao_id = pd.DataFrame({
    "metrica": [
        "Total de registros",
        "IDs únicos",
        "IDs duplicados",
        "Menor ID",
        "Maior ID"
    ],
    "valor": [
        total_linhas,
        ids_unicos,
        ids_duplicados,
        id_minimo,
        id_maximo
    ]
})

validacao_id

              metrica  valor
0  Total de registros   1000
1          IDs únicos   1000
2      IDs duplicados      0
3            Menor ID      1
4            Maior ID   1000

In [15]:
# VALIDAÇÃO TEMPORAL
# ============================================================

df["data"] = pd.to_datetime(df["data"])

datas_invalidas = df["data"].isna().sum()
data_minima = df["data"].min()
data_maxima = df["data"].max()
quantidade_dias_unicos = df["data"].nunique()
periodo_total_dias = (data_maxima - data_minima).days + 1

validacao_temporal = pd.DataFrame({
    "metrica": [
        "Datas inválidas",
        "Data mínima",
        "Data máxima",
        "Quantidade de dias únicos com vendas",
        "Período total em dias"
    ],
    "valor": [
        datas_invalidas,
        data_minima,
        data_maxima,
        quantidade_dias_unicos,
        periodo_total_dias
    ]
})

validacao_temporal

                                metrica                valor
0                       Datas inválidas                    0
1                           Data mínima  2024-01-01 00:00:00
2                           Data máxima  2024-12-30 00:00:00
3  Quantidade de dias únicos com vendas                  338
4                 Período total em dias                  365

In [16]:
# RESUMO CONSOLIDADO DA ANÁLISE DESCRITIVA
# ============================================================

resumo_blocos = pd.DataFrame({
    "bloco": [
        "Atributos qualitativos",
        "Atributos quantitativos",
        "Atributos de identificação/temporais"
    ],
    "quantidade_atributos": [
        len(atributos_qualitativos),
        len(atributos_quantitativos),
        len(atributos_id_temporais)
    ],
    "analises_realizadas": [
        "Valores únicos, frequência absoluta, frequência relativa e moda",
        "Média, mediana, moda, quartis, percentis, assimetria, curtose, dispersão e correlação",
        "Unicidade, duplicidades, limites temporais, volume mensal/trimestral e consistência temporal"
    ]
})

resumo_blocos

,bloco,quantidade_atributos,analises_realizadas
0,Atributos qualitativos,14,"Valores únicos, frequência absoluta, frequênci..."
1,Atributos quantitativos,9,"Média, mediana, moda, quartis, percentis, assi..."
2,Atributos de identificação/temporais,4,"Unicidade, duplicidades, limites temporais, vo..."

## Etapa 4.1 - Análise Estatística Descritiva

A primeira parte da Etapa 4 consistiu na realização de uma análise estatística descritiva da base tratada. Para facilitar a compreensão, os atributos foram separados em três grupos: qualitativos, quantitativos e atributos de identificação/temporais.

Os atributos qualitativos foram analisados por meio da contagem de valores únicos, frequência absoluta, frequência relativa e moda. Essa abordagem permitiu compreender a distribuição das categorias presentes na base, identificando quais produtos, regiões, canais, vendedores, tipos de clientes e status de entrega aparecem com maior frequência. A moda foi utilizada para identificar a categoria predominante em cada variável.

Os atributos quantitativos foram analisados com medidas de tendência central, posição, dispersão e formato da distribuição. Foram calculadas média, mediana, moda, mínimo, máximo, amplitude, desvio padrão, coeficiente de variação, quartis, percentis, assimetria e curtose. Essas estatísticas permitiram compreender o comportamento numérico das variáveis de vendas, como receita, lucro, desconto, preço unitário, custo unitário, quantidade e prazo de entrega.

A análise dos quartis e percentis permitiu observar a distribuição dos valores em diferentes pontos, enquanto a assimetria e a curtose auxiliaram na identificação do formato das distribuições. Histogramas e boxplots foram utilizados para visualizar a distribuição dos atributos quantitativos, e a matriz de correlação foi utilizada para identificar relações lineares entre variáveis numéricas.

Os atributos de identificação e temporais foram analisados separadamente. O identificador `id_venda` foi validado quanto à unicidade, duplicidade e sequência. Já os atributos temporais foram avaliados por meio dos limites de data e período em dias.

Essa análise estatística descritiva forneceu uma visão geral da estrutura e do comportamento da base, servindo como base para as próximas análises da Etapa 4, que envolverão cruzamentos entre variáveis, identificação de padrões e interpretação de relações relevantes para o negócio.

# Cruzamento de Dados
- vendas pro mês
- vendas por trimestre
- vendas por dia
-

In [17]:
# VOLUME DE VENDAS POR MÊS
# ============================================================

volume_mensal = df.groupby("mes").agg(
    quantidade_vendas=("id_venda", "count"),
    receita_total=("receita", "sum"),
    lucro_total=("lucro", "sum")
).reset_index()

volume_mensal["margem_lucro"] = (
    volume_mensal["lucro_total"] / volume_mensal["receita_total"]
)

volume_mensal

    mes  quantidade_vendas  receita_total  lucro_total  margem_lucro
0     1                 93 1,393,767.9698 258,583.4298        0.1855
1     2                 84 1,270,626.7478 276,598.5078        0.2177
2     3                 98 1,432,879.4623 236,255.5323        0.1649
3     4                 81 1,222,590.4084 234,821.8384        0.1921
4     5                 81 1,274,222.9590 314,610.7490        0.2469
5     6                 70 1,074,728.2723 204,117.6923        0.1899
6     7                 80 1,307,184.1022 283,004.5722        0.2165
7     8                 70   990,909.6458 209,072.2258        0.2110
8     9                 69 1,173,685.2836 219,670.5036        0.1872
9    10                 86 1,228,377.9629 236,113.7629        0.1922
10   11                 86 1,345,380.8173 277,571.9473        0.2063
11   12                102 1,481,764.8473 331,383.9173        0.2236

In [18]:
# VOLUME DE VENDAS POR TRIMESTRE
# ============================================================

volume_trimestral = df.groupby("trimestre").agg(
    quantidade_vendas=("id_venda", "count"),
    receita_total=("receita", "sum"),
    lucro_total=("lucro", "sum")
).reset_index()

volume_trimestral["margem_lucro"] = (
    volume_trimestral["lucro_total"] / volume_trimestral["receita_total"]
)

volume_trimestral

   trimestre  quantidade_vendas  receita_total  lucro_total  margem_lucro
0          1                275 4,097,274.1799 771,437.4699        0.1883
1          2                232 3,571,541.6397 753,550.2797        0.2110
2          3                219 3,471,779.0316 711,747.3016        0.2050
3          4                274 4,055,523.6275 845,069.6275        0.2084

In [19]:
# VENDAS POR DIA DA SEMANA
# ============================================================

df["dia_semana"] = df["data"].dt.day_name()

ordem_dias = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

volume_dia_semana = df.groupby("dia_semana").agg(
    quantidade_vendas=("id_venda", "count"),
    receita_total=("receita", "sum"),
    lucro_total=("lucro", "sum")
).reindex(ordem_dias).reset_index()

volume_dia_semana["margem_lucro"] = (
    volume_dia_semana["lucro_total"] / volume_dia_semana["receita_total"]
)

volume_dia_semana

  dia_semana  quantidade_vendas  receita_total  lucro_total  margem_lucro
0     Monday                140 2,119,048.5742 434,232.6642        0.2049
1    Tuesday                141 2,499,405.4828 558,068.5628        0.2233
2  Wednesday                139 1,978,996.2356 406,448.2956        0.2054
3   Thursday                136 2,059,476.6460 412,863.6460        0.2005
4     Friday                159 2,282,684.2910 452,758.7710        0.1983
5   Saturday                139 2,146,386.4790 412,686.8090        0.1923
6     Sunday                146 2,110,120.7701 404,745.9301        0.1918

In [20]:
# SÉRIE TEMPORAL DIÁRIA
# ============================================================

serie_diaria = df.groupby("data").agg(
    quantidade_vendas=("id_venda", "count"),
    receita_total=("receita", "sum"),
    lucro_total=("lucro", "sum")
).reset_index()

serie_diaria["margem_lucro"] = (
    serie_diaria["lucro_total"] / serie_diaria["receita_total"]
)

with pd.option_context('display.max_rows', None):
    display(serie_diaria)

          data  quantidade_vendas  receita_total  lucro_total  margem_lucro
0   2024-01-01                  6   137,202.0932  18,459.5032        0.1345
1   2024-01-02                  5    63,268.5190  10,673.4690        0.1687
2   2024-01-03                  3    29,941.2030   5,887.4330        0.1966
3   2024-01-04                  1     1,938.0900     109.1400        0.0563
4   2024-01-05                  4    87,904.1187  21,563.8987        0.2453
5   2024-01-06                  3    41,924.9950   2,223.8850        0.0530
6   2024-01-07                  1    30,696.5554   1,712.4954        0.0558
7   2024-01-08                  1    26,208.1818     335.7618        0.0128
8   2024-01-09                  2     4,728.9876     900.2676        0.1904
9   2024-01-10                  3    67,258.1816   4,556.3816        0.0677
10  2024-01-11                  5    77,963.9704  12,952.0504        0.1661
11  2024-01-12                  4    88,734.1221   5,569.3821        0.0628
12  2024-01-13                  2    13,488.4144   4,199.8644        0.3114
13  2024-01-14                  4   102,146.3565  29,542.3265        0.2892
14  2024-01-15                  3    64,332.4675  18,856.1475        0.2931
15  2024-01-16                  3    55,172.6865   8,238.5265        0.1493
16  2024-01-17                  3    13,991.6804   3,888.4204        0.2779
17  2024-01-18                  2    52,775.4147  18,276.7447        0.3463
18  2024-01-19                  3    13,230.4193   3,331.5493        0.2518
19  2024-01-20                  3    45,873.9962  14,023.6262        0.3057
20  2024-01-21                  2    15,485.4472   3,130.8672        0.2022
21  2024-01-22                  3    17,933.2384   5,004.1284        0.2790
22  2024-01-23                  3    62,901.8894  14,429.4294        0.2294
23  2024-01-24                  2    31,448.0080   7,402.6780        0.2354
24  2024-01-25                  3    26,201.1318  -1,723.6182       -0.0658
25  2024-01-26                  7    99,255.2279  16,036.6179        0.1616
26  2024-01-27                  3    28,340.2752   4,704.9752        0.1660
27  2024-01-28                  2    19,770.0505     167.7505        0.0085
28  2024-01-29                  1    39,898.2969  17,295.6469        0.4335
29  2024-01-30                  3    19,965.7252   4,516.2352        0.2262
30  2024-01-31                  3    13,788.2260   2,317.8460        0.1681
31  2024-02-01                  8   124,218.6411  30,814.2611        0.2481
32  2024-02-02                  6    59,899.6780     297.5680        0.0050
33  2024-02-03                  2    46,213.9811  16,961.2811        0.3670
34  2024-02-04                  5    90,291.5070  25,427.6470        0.2816
35  2024-02-05                  1    37,482.0296  12,526.0296        0.3342
36  2024-02-07                  1     3,472.5152   1,459.1552        0.4202
37  2024-02-08                  2    40,881.2604   1,898.1504        0.0464
38  2024-02-09                  6   149,314.3878  48,394.7878        0.3241
39  2024-02-10                  1       484.8249     128.7549        0.2656
40  2024-02-11                  1     2,025.9360     194.2560        0.0959
41  2024-02-12                  3    64,257.1314  10,410.6814        0.1620
42  2024-02-13                  4    36,728.4284  14,321.0484        0.3899
43  2024-02-14                  3    17,218.6075   4,218.0675        0.2450
44  2024-02-15                  2    50,973.7806   8,006.6706        0.1571
45  2024-02-16                  4    27,694.2779   7,776.4779        0.2808
46  2024-02-17                  4    39,411.5916   6,507.2216        0.1651
47  2024-02-18                  5    74,495.4750  20,763.7050        0.2787
48  2024-02-19                  3    69,062.4208  12,569.5808        0.1820
49  2024-02-21                  2    15,689.6884   4,354.2884        0.2775
50  2024-02-22                  3    52,110.1738   8,796.3838        0.1688
51  2024-02-23                  3    46,045.2215   1,434.3715        0.0312
52  2024-02-24                  2    16,681.4300   1,813.0300        0.1087
53  2024-02-25                  3    71,256.4086  18,769.3386        0.2634
54  2024-02-26                  3    46,326.5682   6,279.6682        0.1356
55  2024-02-28                  3    43,808.2329   5,664.5629        0.1293
56  2024-02-29                  4    44,582.5501   6,811.5201        0.1528
57  2024-03-01                  2    13,290.1019   5,440.3719        0.4094
58  2024-03-02                  6    72,393.4180  13,348.8280        0.1844
59  2024-03-03                  7    84,403.2217  19,645.7017        0.2328
60  2024-03-05                  1    13,093.5056   2,280.6656        0.1742
61  2024-03-06                  3    35,893.9346   6,239.7846        0.1738
62  2024-03-08                  5    53,381.7912   3,671.4112        0.0688
63  2024-03-09                  3    33,029.3928  10,882.2628        0.3295
64  2024-03-10                  2    27,337.0322   5,732.0122        0.2097
65  2024-03-11                  2    47,674.7688   6,106.9988        0.1281
66  2024-03-12                  4    49,770.6224  13,893.3724        0.2791
67  2024-03-13                  3    20,266.5533   2,815.9333        0.1389
68  2024-03-14                  4    33,945.1516   8,338.6216        0.2456
69  2024-03-15                  8   138,352.3686  18,492.7886        0.1337
70  2024-03-16                  3    73,216.5267   9,522.9967        0.1301
71  2024-03-17                  3    47,267.3456   6,488.4856        0.1373
72  2024-03-18                  4    50,570.5465   6,807.2465        0.1346
73  2024-03-19                  3    31,051.3248   5,604.2548        0.1805
74  2024-03-20                  2    32,645.3916  10,393.2016        0.3184
75  2024-03-21                  4    26,742.2803   4,729.7703        0.1769
76  2024-03-22                  4    73,475.0374   3,519.5874        0.0479
77  2024-03-23                  4   104,703.5189  17,042.6489        0.1628
78  2024-03-24                  1     8,809.6086   2,697.0286        0.3061
79  2024-03-25                  1     2,288.1000     516.3000        0.2256
80  2024-03-26                  5   139,327.6021  21,736.1921        0.1560
81  2024-03-27                  3    30,970.3290   3,824.9390        0.1235
82  2024-03-28                  4    75,332.7858  19,038.4658        0.2527
83  2024-03-29                  3    48,808.6525   6,454.9025        0.1322
84  2024-03-31                  4    64,838.5498     990.7598        0.0153
85  2024-04-01                  4    55,227.8177   8,892.5577        0.1610
86  2024-04-03                  1    42,418.6488  15,697.3788        0.3701
87  2024-04-04                  2    22,569.1470   5,458.3070        0.2418
88  2024-04-05                  1     6,180.9920   2,439.6420        0.3947
89  2024-04-06                  3    75,553.5770  14,436.2570        0.1911
90  2024-04-08                  1    39,828.2082   9,813.8282        0.2464
91  2024-04-09                  4    77,725.6005  17,903.9705        0.2303
92  2024-04-10                  3    51,725.5530  18,997.9330        0.3673
93  2024-04-11                  1     2,386.9120     956.7520        0.4008
94  2024-04-12                  3    26,148.6227   4,157.8027        0.1590
95  2024-04-13                  2    25,272.4500  -3,037.3200       -0.1202
96  2024-04-14                  4    63,355.2921   8,211.7121        0.1296
97  2024-04-15                  4    19,095.8264   3,174.8264        0.1663
98  2024-04-16                  4    61,189.0168   3,347.0268        0.0547
99  2024-04-17                  1    11,818.1472     166.9472        0.0141
100 2024-04-18                  3    51,246.6339   3,833.5639        0.0748
101 2024-04-19                  1    21,458.5146   3,494.6046        0.1629
102 2024-04-20                  3    48,379.3224   9,903.4324        0.2047
103 2024-04-21                  3    26,668.4935   5,571.3035        0.2089
104 2024-04-22                  4    42,608.8354  11,806.5354        0.2771
105 2024-04-23                  2    39,570.9872  16,220.3472        0.4099
106 2024-04-24                  6    53,236.4103  11,755.4903        0.2208
107 2024-04-25                  4    33,886.1155   8,185.4155        0.2416
108 2024-04-26                  3    50,339.4272  13,196.6472        0.2622
109 2024-04-27                  1     4,176.0342     193.1242        0.0462
110 2024-04-28                  4    74,652.9185  13,451.5185        0.1802
111 2024-04-29                  4    84,633.8079   6,375.3279        0.0753
112 2024-04-30                  5   111,237.0964  20,216.9064        0.1817
113 2024-05-01                  5    80,208.1644  23,025.6044        0.2871
114 2024-05-02                  3    19,523.5166   6,492.1366        0.3325
115 2024-05-03                  3    58,911.5176  21,153.8876        0.3591
116 2024-05-04                  3    49,542.8710  15,189.6910        0.3066
117 2024-05-05                  1    26,363.5074   6,448.4274        0.2446
118 2024-05-06                  2    27,055.7668   6,489.3668        0.2399
119 2024-05-07                  3    20,982.5837   3,140.1637        0.1497
120 2024-05-08                  4    83,663.1626  14,208.7226        0.1698
121 2024-05-09                  2    29,298.7250   6,396.6350        0.2183
122 2024-05-10                  4    80,368.2516  22,757.0616        0.2832
123 2024-05-11                  3    16,103.2940   3,297.8740        0.2048
124 2024-05-12                  2    76,942.9370  18,119.1870        0.2355
125 2024-05-13                  1     2,865.6747    -120.5853       -0.0421
126 2024-05-14                  7   140,680.3983  48,315.6983        0.3434
127 2024-05-15                  3    12,643.5964   3,170.9664        0.2508
128 2024-05-17                  4    75,211.6248  17,026.6348        0.2264
129 2024-05-18                  4   109,585.4499  36,309.0099        0.3313
130 2024-05-19                  1     1,394.2394      85.1994        0.0611
131 2024-05-20                  1     2,031.8396     945.9596        0.4656
132 2024-05-21                  1    23,009.8410   8,761.5810        0.3808
133 2024-05-22                  6    76,680.7472  18,690.1072        0.2437
134 2024-05-23                  1     6,738.5280   2,140.3480        0.3176
135 2024-05-24                  2    46,415.8009  14,397.8109        0.3102
136 2024-05-25                  2    36,694.7438   5,611.3238        0.1529
137 2024-05-26                  4    75,884.0981    -719.9119       -0.0095
138 2024-05-27                  2     4,178.8852   1,130.2652        0.2705
139 2024-05-29                  4    65,121.1100   6,276.9000        0.0964
140 2024-05-30                  2    10,852.2472   1,077.0872        0.0993
141 2024-05-31                  1    15,269.8368   4,793.5968        0.3139
142 2024-06-01                  1    15,641.2165   1,767.7765        0.1130
143 2024-06-02                  3    53,134.4895  15,387.4595        0.2896
144 2024-06-03                  3    16,695.5256     928.2756        0.0556
145 2024-06-04                  1     1,704.2784     533.7284        0.3132
146 2024-06-05                  2    32,189.8510   7,490.8410        0.2327
147 2024-06-06                  2    31,031.5068   6,184.9068        0.1993
148 2024-06-07                  3    30,093.9992   8,123.7192        0.2699
149 2024-06-08                  3    69,483.2740  16,599.3540        0.2389
150 2024-06-09                  3    46,414.2980   4,662.0380        0.1004
151 2024-06-10                  3    60,270.9984  21,286.0284        0.3532
152 2024-06-11                  1     9,216.9760   2,702.7760        0.2932
153 2024-06-12                  4    85,627.3222  20,189.4822        0.2358
154 2024-06-13                  2    17,582.4552   3,776.9152        0.2148
155 2024-06-14                  5   100,748.5300  21,101.8100        0.2095
156 2024-06-15                  1    13,956.7965   2,397.8565        0.1718
157 2024-06-16                  3    33,500.6916   1,891.1916        0.0565
158 2024-06-17                  2    40,389.5104  -1,475.0896       -0.0365
159 2024-06-18                  2    37,272.8790  -3,574.7610       -0.0959
160 2024-06-19                  1    24,511.8636   6,064.2036        0.2474
161 2024-06-21                  3    21,498.7608   4,405.8108        0.2049
162 2024-06-22                  4    55,089.2343   4,725.9443        0.0858
163 2024-06-23                  1    12,564.3150     789.7950        0.0629
164 2024-06-24                  1     9,264.6048   2,835.9648        0.3061
165 2024-06-26                  3   128,684.9646  37,581.2446        0.2920
166 2024-06-27                  3    61,653.6844   1,013.9444        0.0164
167 2024-06-28                  4    29,522.8939   7,520.5739        0.2547
168 2024-06-29                  3    21,182.7852   5,035.8052        0.2377
169 2024-06-30                  3    15,800.5674   4,170.0974        0.2639
170 2024-07-01                  5   108,089.0558  36,926.8958        0.3416
171 2024-07-02                  4    49,845.4149  17,920.5949        0.3595
172 2024-07-03                  2    42,897.3868   4,238.5268        0.0988
173 2024-07-04                  4    92,436.1008  25,939.3808        0.2806
174 2024-07-05                  4    49,707.8973   9,705.5873        0.1953
175 2024-07-06                  2    25,789.6944   5,031.1244        0.1951
176 2024-07-07                  1     9,267.8796   4,457.7396        0.4810
177 2024-07-08                  2    20,132.9495   1,707.7195        0.0848
178 2024-07-09                  1    20,143.2528   4,215.5328        0.2093
179 2024-07-10                  4    55,586.1752  11,048.8952        0.1988
180 2024-07-11                  2    51,146.8216   2,356.1816        0.0461
181 2024-07-12                  3    62,003.0850  17,638.7350        0.2845
182 2024-07-13                  2    24,090.5018     393.8218        0.0163
183 2024-07-14                  4    79,128.5223  17,434.6723        0.2203
184 2024-07-15                  2    27,102.5247   5,720.3147        0.2111
185 2024-07-16                  2    82,347.4159  35,293.9859        0.4286
186 2024-07-17                  3    37,031.9070  10,752.5170        0.2904
187 2024-07-18                  2    17,135.9253   1,291.4253        0.0754
188 2024-07-19                  2    23,810.3480   1,333.8480        0.0560
189 2024-07-20                  5    80,684.0182  13,048.1882        0.1617
190 2024-07-22                  6    75,110.0846  18,047.6246        0.2403
191 2024-07-23                  2    38,261.5470   4,960.6170        0.1297
192 2024-07-24                  2     6,493.8364     647.6564        0.0997
193 2024-07-25                  1    41,647.9140   2,212.7140        0.0531
194 2024-07-26                  2    23,326.2888   4,404.2388        0.1888
195 2024-07-27                  2    14,319.0600   4,269.1200        0.2981
196 2024-07-28                  2    29,124.7430   7,603.1430        0.2611
197 2024-07-29                  2    28,142.6525   3,708.1125        0.1318
198 2024-07-30                  1    44,773.0920  -5,323.1080       -0.1189
199 2024-07-31                  4    47,608.0070  16,018.7670        0.3365
200 2024-08-01                  3    30,170.4072  10,264.8272        0.3402
201 2024-08-02                  2     5,317.9922   1,154.3222        0.2171
202 2024-08-03                  2    32,472.8622  12,079.6122        0.3720
203 2024-08-04                  3    41,403.3762   4,815.1662        0.1163
204 2024-08-06                  5    75,134.0177  25,138.5177        0.3346
205 2024-08-07                  4    59,389.5280  10,032.5580        0.1689
206 2024-08-08                  1     1,281.2625     231.8325        0.1809
207 2024-08-10                  2    21,915.6861   3,883.7361        0.1772
208 2024-08-11                  6    99,727.7036  10,466.8736        0.1050
209 2024-08-12                  3    11,622.6864     862.4864        0.0742
210 2024-08-13                  2    49,181.1173  17,851.2873        0.3630
211 2024-08-14                  2    22,243.7280   3,027.2080        0.1361
212 2024-08-15                  3    58,164.2984   1,540.8984        0.0265
213 2024-08-17                  2    43,557.4970  14,036.6470        0.3223
214 2024-08-18                  3    14,734.7538   3,592.2638        0.2438
215 2024-08-19                  1    45,618.5520  17,325.6520        0.3798
216 2024-08-20                  5   118,491.1370  12,502.5270        0.1055
217 2024-08-21                  2    19,990.9230   4,595.4230        0.2299
218 2024-08-22                  2    65,426.1485  13,106.3985        0.2003
219 2024-08-24                  1    15,038.3304     590.8104        0.0393
220 2024-08-25                  2    15,384.0046   5,897.5946        0.3834
221 2024-08-26                  3    61,470.3253  19,887.0253        0.3235
222 2024-08-27                  3     9,782.8241   2,112.9041        0.2160
223 2024-08-28                  4    46,536.3539   4,337.3639        0.0932
224 2024-08-29                  2    18,551.7888   6,951.4788        0.3747
225 2024-08-30                  2     8,302.3416   2,786.8116        0.3357
226 2024-09-02                  2    44,154.6756  -3,134.5644       -0.0710
227 2024-09-03                  3    59,085.8619   8,330.5119        0.1410
228 2024-09-04                  1     6,333.3744   1,806.1744        0.2852
229 2024-09-05                  1     8,807.2428    -111.4572       -0.0127
230 2024-09-06                  2    38,510.7993   7,550.0693        0.1961
231 2024-09-07                  4    30,137.2736   3,161.0336        0.1049
232 2024-09-09                  3    28,359.3956   1,741.3156        0.0614
233 2024-09-10                  2    70,178.6028  19,503.6628        0.2779
234 2024-09-11                  1    11,524.6068   1,576.4268        0.1368
235 2024-09-12                  3    56,923.0231  14,816.9931        0.2603
236 2024-09-13                  5    94,012.8734  18,034.7534        0.1918
237 2024-09-15                  4    65,753.1373   4,368.2773        0.0664
238 2024-09-17                  5    81,129.6420  27,640.4820        0.3407
239 2024-09-18                  2    35,220.7362   6,464.7562        0.1835
240 2024-09-20                  2    56,649.5012  11,459.1112        0.2023
241 2024-09-21                  3    65,303.3933  12,848.5333        0.1968
242 2024-09-22                  2     8,947.7010     551.9910        0.0617
243 2024-09-23                  2    23,820.9833  -2,948.8767       -0.1238
244 2024-09-24                  4   111,199.8099  26,877.8999        0.2417
245 2024-09-25                  1    14,173.5936   5,086.4736        0.3589
246 2024-09-26                  2    48,038.2448  17,496.6048        0.3642
247 2024-09-27                  1    17,155.5426   2,368.6026        0.1381
248 2024-09-28                  5    78,214.7135  15,563.6835        0.1990
249 2024-09-29                  5    32,129.9573   6,629.1073        0.2063
250 2024-09-30                  4    87,920.5983  11,988.9383        0.1364
251 2024-10-01                  1     1,946.8646     632.7146        0.3250
252 2024-10-02                  3    27,392.9867  -1,513.6433       -0.0553
253 2024-10-03                  4    34,628.4187   5,829.9087        0.1684
254 2024-10-04                  1    57,799.6672  12,765.3372        0.2209
255 2024-10-05                  3    55,876.3457   3,615.7057        0.0647
256 2024-10-06                  2    13,635.1760   2,425.8660        0.1779
257 2024-10-07                  2    31,847.0521   6,562.3521        0.2061
258 2024-10-08                  4    81,883.1503  14,683.2103        0.1793
259 2024-10-09                  2    11,231.8356   2,225.7556        0.1982
260 2024-10-10                  3    19,847.3255     726.1355        0.0366
261 2024-10-11                  2    27,971.1019   5,138.6419        0.1837

# Análise Atributos e KPIs

[quantidade_vendas, quantidade_itens, receita, lucro, desconto_medio, media_total, taxa_meta, taxa_atraso, margem_lucro, ticket_medio]  = KPIs

- Região
- Canal de venda
- Categoria
- Produto
- Tipo de cliente
- Vendedor

In [22]:
# FUNÇÃO AUXILIAR PARA CRUZAMENTOS
# ============================================================

def analisar_dimensao(base, dimensao):
    """
    Agrupa a base por uma dimensão categórica e calcula os principais KPIs.
    """
    
    analise = base.groupby(dimensao, observed=True).agg(
        vendas=("id_venda", "count"),
        quantidade=("quantidade", "sum"),
        receita=("receita", "sum"),
        lucro=("lucro", "sum"),
        desconto_medio=("desconto", "mean"),
        meta_total=("meta_venda", "sum"),
        taxa_meta=("atingiu_meta", lambda x: (x == "Sim").mean()),
        taxa_atraso=("status_entrega", lambda x: (x == "Atrasado").mean())
    )
    
    analise["margem_lucro"] = analise["lucro"] / analise["receita"]
    analise["ticket_medio"] = analise["receita"] / analise["vendas"]
    
    return analise.sort_values("receita", ascending=False)

In [23]:
# 4.3 - ANÁLISE POR REGIÃO
# ============================================================

analise_regiao = analisar_dimensao(df, "regiao")

analise_regiao

,vendas,quantidade,receita,lucro,desconto_medio,meta_total,taxa_meta,taxa_atraso,margem_lucro,ticket_medio
regiao,,,,,,,,,,
Sul,209,1253,"3,314,346.5699","732,603.3099",0.1247,"3,984,848.2000",0.0478,0.5502,0.2210,"15,858.1176"
Centro-Oeste,202,1273,"3,265,071.8116","586,749.5016",0.1376,"4,006,791.2100",0.0545,0.4901,0.1797,"16,163.7218"
Norte,209,1278,"3,247,788.9366","689,213.0166",0.1186,"3,834,767.9300",0.1053,0.5215,0.2122,"15,539.6600"
Sudeste,199,1197,"2,720,463.9033","527,492.3733",0.1304,"3,322,269.1500",0.0653,0.5276,0.1939,"13,670.6729"
Nordeste,181,1061,"2,648,447.2573","545,746.4773",0.1304,"3,204,968.0300",0.0773,0.5028,0.2061,"14,632.3053"

In [24]:
# 4.4 - ANÁLISE POR CANAL DE VENDA
# ============================================================

analise_canal = analisar_dimensao(df, "canal_venda")

analise_canal

,vendas,quantidade,receita,lucro,desconto_medio,meta_total,taxa_meta,taxa_atraso,margem_lucro,ticket_medio
canal_venda,,,,,,,,,,
Online,522,3169,"8,092,223.7471","1,600,532.6771",0.1300,"9,830,537.0200",0.0747,0.4885,0.1978,"15,502.3443"
Loja,478,2893,"7,103,894.7316","1,481,272.0016",0.1263,"8,523,107.5000",0.0649,0.5523,0.2085,"14,861.7045"

In [25]:
# 4.5 - ANÁLISE POR CATEGORIA
# ============================================================

analise_categoria = analisar_dimensao(df, "categoria")

analise_categoria

,vendas,quantidade,receita,lucro,desconto_medio,meta_total,taxa_meta,taxa_atraso,margem_lucro,ticket_medio
categoria,,,,,,,,,,
Informática,492,3021,"7,297,489.8756","1,502,208.4156",0.1276,"8,764,772.1100",0.0813,0.5041,0.2059,"14,832.2965"
Periféricos,346,2029,"5,432,341.1166","1,091,976.2666",0.1269,"6,617,255.8400",0.0636,0.5491,0.2010,"15,700.4079"
Telefonia,132,800,"1,934,879.5352","399,791.5652",0.1345,"2,333,209.6900",0.0379,0.4924,0.2066,"14,658.1783"
Outros,30,212,"531,407.9513","87,828.4313",0.1250,"638,406.8800",0.1000,0.5333,0.1653,"17,713.5984"

In [26]:
# 4.6 - ANÁLISE POR PRODUTO
# ============================================================

analise_produto = analisar_dimensao(df, "produto")

analise_produto

,vendas,quantidade,receita,lucro,desconto_medio,meta_total,taxa_meta,taxa_atraso,margem_lucro,ticket_medio
produto,,,,,,,,,,
Monitor,143,960,"2,463,025.3196","448,537.8596",0.1306,"2,980,361.9600",0.1049,0.5245,0.1821,"17,223.9533"
Teclado,115,683,"1,973,461.4424","425,008.6724",0.1312,"2,372,065.2300",0.0522,0.5739,0.2154,"17,160.5343"
Mouse,133,796,"1,962,335.2508","389,571.5908",0.1176,"2,381,767.6700",0.0827,0.5338,0.1985,"14,754.4004"
Smartphone,133,805,"1,946,475.0212","402,535.9512",0.1347,"2,347,534.6400",0.0376,0.4887,0.2068,"14,635.1505"
Impressora,115,724,"1,859,469.9215","419,170.2815",0.1322,"2,259,276.6200",0.0609,0.5130,0.2254,"16,169.3037"
Headset,111,644,"1,697,277.7110","310,612.3510",0.1352,"2,100,652.0800",0.0541,0.5405,0.1830,"15,290.7902"
Notebook,122,719,"1,647,800.9065","386,693.2165",0.1185,"1,947,316.0100",0.0820,0.5246,0.2347,"13,506.5648"
Tablet,128,731,"1,646,272.9057","299,674.7557",0.1266,"1,964,670.3100",0.0781,0.4609,0.1820,"12,861.5071"

In [27]:
# 4.7 - ANÁLISE POR TIPO DE CLIENTE
# ============================================================

analise_tipo_cliente = analisar_dimensao(df, "tipo_cliente")

analise_tipo_cliente

,vendas,quantidade,receita,lucro,desconto_medio,meta_total,taxa_meta,taxa_atraso,margem_lucro,ticket_medio
tipo_cliente,,,,,,,,,,
Recorrente,519,3186,"7,853,078.6324","1,578,620.5424",0.1287,"9,532,590.8900",0.0809,0.4855,0.2010,"15,131.1727"
Novo,481,2876,"7,343,039.8463","1,503,184.1363",0.1276,"8,821,053.6300",0.0582,0.5551,0.2047,"15,266.1951"

In [28]:
# 4.8 - ANÁLISE POR VENDEDOR
# ============================================================

analise_vendedor = analisar_dimensao(df, "vendedor")

# Top 10 vendedores por receita
top_vendedores_receita = analise_vendedor.sort_values("receita", ascending=False)

top_vendedores_receita

,vendas,quantidade,receita,lucro,desconto_medio,meta_total,taxa_meta,taxa_atraso,margem_lucro,ticket_medio
vendedor,,,,,,,,,,
Vendedor_13,60,384,"1,050,462.6194","206,493.8594",0.1299,"1,249,363.0400",0.0667,0.5000,0.1966,"17,507.7103"
Vendedor_18,53,329,"958,083.4186","203,100.3786",0.1248,"1,163,375.2200",0.0755,0.3585,0.2120,"18,077.0456"
Vendedor_12,60,382,"939,076.5662","153,868.6462",0.1296,"1,177,067.8900",0.0333,0.4833,0.1639,"15,651.2761"
Vendedor_19,50,326,"908,888.4283","189,655.6283",0.1462,"1,119,304.1500",0.0600,0.5000,0.2087,"18,177.7686"
Vendedor_20,49,313,"905,934.0195","239,532.8195",0.1269,"1,101,882.5600",0.0612,0.5510,0.2644,"18,488.4494"
Vendedor_10,63,367,"832,485.6311","187,059.0811",0.1324,"984,022.4000",0.0317,0.6190,0.2247,"13,214.0576"
Vendedor_08,46,345,"809,109.5116","161,494.0416",0.1388,"985,587.5500",0.0217,0.6304,0.1996,"17,589.3372"
Vendedor_17,50,317,"800,704.4098","157,393.4398",0.1194,"937,353.4100",0.1400,0.4600,0.1966,"16,014.0882"
Vendedor_03,50,277,"787,685.1876","130,323.1076",0.1208,"924,067.0900",0.2000,0.5600,0.1655,"15,753.7038"
Vendedor_04,55,314,"783,594.9500","193,736.3400",0.1129,"936,440.0300",0.1273,0.4000,0.2472,"14,247.1809"
Vendedor_06,50,282,"733,731.7434","165,302.8134",0.1202,"882,202.4500",0.0200,0.5600,0.2253,"14,674.6349"
Vendedor_02,48,291,"723,128.0519","159,101.6319",0.1056,"839,212.9900",0.1667,0.5625,0.2200,"15,065.1677"
Vendedor_01,44,261,"702,029.8713","146,605.8213",0.1384,"841,468.8500",0.0682,0.5455,0.2088,"15,955.2243"
Vendedor_11,48,305,"691,955.7690","126,911.3290",0.1353,"849,074.6700",0.0417,0.5417,0.1834,"14,415.7452"
Vendedor_14,41,252,"688,737.9280","119,701.9180",0.1334,"844,855.8400",0.0732,0.4634,0.1738,"16,798.4860"
Vendedor_05,49,287,"654,102.0700","137,205.5400",0.1242,"785,938.2600",0.0612,0.5306,0.2098,"13,349.0218"
Vendedor_07,48,275,"591,373.6110","115,382.0510",0.1335,"719,129.4900",0.0625,0.5417,0.1951,"12,320.2836"
Vendedor_15,47,275,"552,040.1416","82,327.8216",0.1434,"691,975.9500",0.0000,0.5106,0.1491,"11,745.5349"
Vendedor_09,46,236,"549,973.1801","95,398.9301",0.1257,"662,268.0800",0.0435,0.5000,0.1735,"11,955.9387"
Vendedor_16,43,244,"533,021.3703","111,209.4803",0.1252,"659,054.6000",0.0465,0.5814,0.2086,"12,395.8458"

# Cruzamento - Respostas as Perguntas de Negócio

In [29]:
# ETAPA 4.4 - CORRELAÇÕES, CRUZAMENTOS E RELAÇÕES DE NEGÓCIO
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path
from matplotlib.ticker import FuncFormatter
from IPython.display import display

# Configurações
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.float_format", "{:,.4f}".format)

sns.set_theme(style="whitegrid")

plt.rcParams["figure.figsize"] = (10, 5)
plt.rcParams["axes.titlesize"] = 14
plt.rcParams["axes.labelsize"] = 11
plt.rcParams["xtick.labelsize"] = 10
plt.rcParams["ytick.labelsize"] = 10


# CARREGAMENTO DA BASE TRATADA
# ============================================================

caminho_base = Path("dados_empresa_tratado.csv")

if not caminho_base.exists():
    raise FileNotFoundError(
        "O arquivo 'dados_empresa_tratado.csv' não foi encontrado. "
        "Verifique se ele está na mesma pasta deste notebook."
    )

df = pd.read_csv(caminho_base)

# Converter data
df["data"] = pd.to_datetime(df["data"], errors="coerce")

# Criar variável numérica para atingimento de meta
df["atingiu_meta_flag"] = np.where(df["atingiu_meta"] == "Sim", 1, 0)

# Criar margem de lucro por venda
df["margem_lucro_venda"] = df["lucro"] / df["receita"]

In [30]:
# FUNÇÕES AUXILIARES
# ============================================================

def eixo_moeda(x, pos):
    if abs(x) >= 1_000_000:
        return f"R$ {x/1_000_000:.1f} mi"
    elif abs(x) >= 1_000:
        return f"R$ {x/1_000:.0f} mil"
    else:
        return f"R$ {x:.0f}"


def eixo_percentual(x, pos):
    return f"{x:.0%}"


def formatar_moeda(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")


def formatar_percentual(valor):
    return f"{valor:.2%}".replace(".", ",")

## Regiões vs. Receita e Margem de Lucro

Responder à pergunta: **Quais regiões geram maior receita e quais apresentam menor margem de lucro?**
    
Será calculado:  
- soma da receita;
- soma do lucro;
- margem de lucro agregada. (margem_lucro = lucro_total / receita_total)

In [31]:
# REGIÕES VS. RECEITA E MARGEM DE LUCRO
# ============================================================

analise_regiao = df.groupby("regiao").agg(
    quantidade_vendas=("id_venda", "count"),
    receita_total=("receita", "sum"),
    lucro_total=("lucro", "sum")
).reset_index()

analise_regiao["margem_lucro"] = (
    analise_regiao["lucro_total"] / analise_regiao["receita_total"]
)

analise_regiao = analise_regiao.sort_values("receita_total", ascending=False)

analise_regiao

         regiao  quantidade_vendas  receita_total  lucro_total  margem_lucro
4           Sul                209 3,314,346.5699 732,603.3099        0.2210
0  Centro-Oeste                202 3,265,071.8116 586,749.5016        0.1797
2         Norte                209 3,247,788.9366 689,213.0166        0.2122
3       Sudeste                199 2,720,463.9033 527,492.3733        0.1939
1      Nordeste                181 2,648,447.2573 545,746.4773        0.2061

## Produtos e Categorias vs. Volume e Lucro

Responder à pergunta: **Quais produtos e categorias são mais vendidos e quais geram maior lucro?**  

Será calculado:
- soma da quantidade;
- soma do lucro.

In [32]:
# PRODUTOS E CATEGORIAS VS. VOLUME E LUCRO
# ============================================================

import pandas as pd

analise_categoria = (
    df.groupby("categoria")
    .agg(quantidade_total=("quantidade", "sum"), lucro_total=("lucro", "sum"))
    .reset_index()
)

analise_categoria = analise_categoria.sort_values(
    "lucro_total", ascending=False
).round(2)

analise_produto = (
    df.groupby("produto")
    .agg(quantidade_total=("quantidade", "sum"), lucro_total=("lucro", "sum"))
    .reset_index()
)

analise_produto = analise_produto.sort_values(
    "lucro_total", ascending=False
).round(2)

print("--- DESEMPENHO POR CATEGORIA ---")
display(analise_categoria) 

print("\n--- DESEMPENHO POR PRODUTO ---")
display(analise_produto)

analise_categoria_produto = df.groupby(["categoria", "produto"]).agg(
    quantidade_total=("quantidade", "sum"),
    lucro_total=("lucro", "sum")
).reset_index()

analise_categoria_produto = analise_categoria_produto.sort_values(
    "lucro_total",
    ascending=False
)

print("\n--- DESEMPENHO POR CATEGORIA-PRODUTO ---")
analise_categoria_produto

--- DESEMPENHO POR CATEGORIA ---

     categoria  quantidade_total    lucro_total
0  Informática              3021 1,502,208.4200
2  Periféricos              2029 1,091,976.2700
3    Telefonia               800   399,791.5700
1       Outros               212    87,828.4300

--- DESEMPENHO POR PRODUTO ---

      produto  quantidade_total  lucro_total
2     Monitor               960 448,537.8600
7     Teclado               683 425,008.6700
1  Impressora               724 419,170.2800
5  Smartphone               805 402,535.9500
3       Mouse               796 389,571.5900
4    Notebook               719 386,693.2200
0     Headset               644 310,612.3500
6      Tablet               731 299,674.7600

--- DESEMPENHO POR CATEGORIA-PRODUTO ---

      categoria     produto  quantidade_total  lucro_total
1   Informática     Monitor               931 440,159.9034
14  Periféricos     Teclado               629 413,047.0036
0   Informática  Impressora               688 410,719.7664
15    Telefonia  Smartphone               800 399,791.5652
13  Periféricos       Mouse               769 372,363.3626
2   Informática    Notebook               685 369,480.7685
12  Periféricos     Headset               631 306,565.9004
3   Informática      Tablet               717 281,847.9773
10       Outros      Tablet                14  17,826.7784
8        Outros    Notebook                34  17,212.4480
7        Outros       Mouse                27  17,208.2282
11       Outros     Teclado                54  11,961.6688
5        Outros  Impressora                36   8,450.5151
6        Outros     Monitor                29   8,377.9562
4        Outros     Headset                13   4,046.4506
9        Outros  Smartphone                 5   2,744.3860

## Canal de Venda — Online vs. Loja Física

Responde à pergunta: **O canal online apresenta desempenho melhor ou pior que a loja física?**  

Agrupar por canal_venda e analisar:  
- receita total;
- lucro total;
- média de atingiu_meta.  
Como atingiu_meta é textual, usamos a versão numérica atingiu_meta_flag: Sim = 1 | Não = 0  
A média dessa variável representa a taxa de atingimento de meta.

In [33]:
# CANAL DE VENDA VS. RECEITA, LUCRO E META
# ============================================================

analise_canal = df.groupby("canal_venda").agg(
    quantidade_vendas=("id_venda", "count"),
    receita_total=("receita", "sum"),
    lucro_total=("lucro", "sum"),
    taxa_atingiu_meta=("atingiu_meta_flag", "mean")
).reset_index()

analise_canal["margem_lucro"] = (
    analise_canal["lucro_total"] / analise_canal["receita_total"]
)

analise_canal = analise_canal.sort_values("receita_total", ascending=False)

analise_canal

,canal_venda,quantidade_vendas,receita_total,lucro_total,taxa_atingiu_meta,margem_lucro
1,Online,522,"8,092,223.7471","1,600,532.6771",0.0747,0.1978
0,Loja,478,"7,103,894.7316","1,481,272.0016",0.0649,0.2085

## Desempenho da Equipe Comercial — Vendedores

Responde à pergunta: **Quais vendedores possuem melhor desempenho em receita, lucro e cumprimento de metas?**  

Agrupa por vendedor, calcula:
- soma da receita;
- soma do lucro;
- porcentagem de atingimento de meta.

In [34]:
# DESEMPENHO DA EQUIPE COMERCIAL
# ============================================================

analise_vendedor = df.groupby("vendedor").agg(
    quantidade_vendas=("id_venda", "count"),
    receita_total=("receita", "sum"),
    lucro_total=("lucro", "sum"),
    taxa_atingiu_meta=("atingiu_meta_flag", "mean")
).reset_index()

analise_vendedor["margem_lucro"] = (
    analise_vendedor["lucro_total"] / analise_vendedor["receita_total"]
)

analise_vendedor = analise_vendedor.sort_values(
    "lucro_total",
    ascending=False
)

analise_vendedor

,vendedor,quantidade_vendas,receita_total,lucro_total,taxa_atingiu_meta,margem_lucro
19,Vendedor_20,49,"905,934.0195","239,532.8195",0.0612,0.2644
12,Vendedor_13,60,"1,050,462.6194","206,493.8594",0.0667,0.1966
17,Vendedor_18,53,"958,083.4186","203,100.3786",0.0755,0.2120
3,Vendedor_04,55,"783,594.9500","193,736.3400",0.1273,0.2472
18,Vendedor_19,50,"908,888.4283","189,655.6283",0.0600,0.2087
9,Vendedor_10,63,"832,485.6311","187,059.0811",0.0317,0.2247
5,Vendedor_06,50,"733,731.7434","165,302.8134",0.0200,0.2253
7,Vendedor_08,46,"809,109.5116","161,494.0416",0.0217,0.1996
1,Vendedor_02,48,"723,128.0519","159,101.6319",0.1667,0.2200
16,Vendedor_17,50,"800,704.4098","157,393.4398",0.1400,0.1966
11,Vendedor_12,60,"939,076.5662","153,868.6462",0.0333,0.1639
0,Vendedor_01,44,"702,029.8713","146,605.8213",0.0682,0.2088
4,Vendedor_05,49,"654,102.0700","137,205.5400",0.0612,0.2098
2,Vendedor_03,50,"787,685.1876","130,323.1076",0.2000,0.1655
10,Vendedor_11,48,"691,955.7690","126,911.3290",0.0417,0.1834
13,Vendedor_14,41,"688,737.9280","119,701.9180",0.0732,0.1738
6,Vendedor_07,48,"591,373.6110","115,382.0510",0.0625,0.1951
15,Vendedor_16,43,"533,021.3703","111,209.4803",0.0465,0.2086
8,Vendedor_09,46,"549,973.1801","95,398.9301",0.0435,0.1735
14,Vendedor_15,47,"552,040.1416","82,327.8216",0.0000,0.1491

## Fidelidade do Cliente — Recorrentes vs. Novos

Responde à pergunta: **Clientes recorrentes geram maior receita e lucro do que clientes novos?**  

Agrupa por tipo_cliente, calcula:
- soma da receita;
- soma do lucro;
- margem de lucro.

In [35]:
# FIDELIDADE DO CLIENTE - RECORRENTES VS. NOVOS
# ============================================================

analise_tipo_cliente = df.groupby("tipo_cliente").agg(
    quantidade_vendas=("id_venda", "count"),
    receita_total=("receita", "sum"),
    lucro_total=("lucro", "sum")
).reset_index()

analise_tipo_cliente["margem_lucro"] = (
    analise_tipo_cliente["lucro_total"] / analise_tipo_cliente["receita_total"]
)

analise_tipo_cliente = analise_tipo_cliente.sort_values(
    "receita_total",
    ascending=False
)

analise_tipo_cliente

  tipo_cliente  quantidade_vendas  receita_total    lucro_total  margem_lucro
1   Recorrente                519 7,853,078.6324 1,578,620.5424        0.2010
0         Novo                481 7,343,039.8463 1,503,184.1363        0.2047

## Impacto dos Descontos na Margem de Lucro

Responde à pergunta: **O nível de desconto concedido impacta negativamente a margem de lucro?**  

Correlação estatística real, calcular:
- correlação de Pearson, que mede relação linear.
- correlação de Spearman, que mede relação monotônica, mesmo que não seja perfeitamente linear.

In [36]:
# IMPACTO DOS DESCONTOS NA MARGEM DE LUCRO
# ============================================================

# 1. Garante a criação da coluna de margem de lucro
df["margem_lucro_venda"] = np.where(
    df["receita"] != 0, df["lucro"] / df["receita"], 0
)


# 2. Cria uma regra simples para classificar o tamanho do desconto dado na venda
def agrupar_desconto(valor):
    if valor == 0:
        return "1. Sem Desconto (0%)"
    elif valor <= 0.10:
        return "2. Desconto Baixo (Até 10%)"
    elif valor <= 0.20:
        return "3. Desconto Moderado (11% a 20%)"
    else:
        return "4. Desconto Alto (Acima de 20%)"


# Aplica a regra na base de dados
df["Faixa de Desconto"] = df["desconto"].apply(agrupar_desconto)

# 3. Agrupa os dados para ver o impacto real na margem e no lucro médio
relatorio_simples = (
    df.groupby("Faixa de Desconto")
    .agg(
        total_vendas=("id_venda", "count"),
        desconto_medio=("desconto", "mean"),
        margem_lucro_media=("margem_lucro_venda", "mean"),
        lucro_medio_por_venda=("lucro", "mean"),
    )
    .reset_index()
)

# Formata as colunas para porcentagem e moeda para ficar fácil de ler
relatorio_simples["desconto_medio"] = (
    relatorio_simples["desconto_medio"] * 100
).round(1).astype(str) + "%"
relatorio_simples["margem_lucro_media"] = (
    relatorio_simples["margem_lucro_media"] * 100
).round(1).astype(str) + "%"
relatorio_simples["lucro_medio_por_venda"] = (
    "R$ " + relatorio_simples["lucro_medio_por_venda"].round(2).astype(str)
)

relatorio_simples

,Faixa de Desconto,total_vendas,desconto_medio,margem_lucro_media,lucro_medio_por_venda
0,1. Sem Desconto (0%),20,0.0%,29.4%,R$ 6065.05
1,2. Desconto Baixo (Até 10%),365,5.5%,26.9%,R$ 4246.77
2,3. Desconto Moderado (11% a 20%),437,15.5%,17.0%,R$ 2736.42
3,4. Desconto Alto (Acima de 20%),178,22.7%,10.2%,R$ 1205.71

# Análise de Pareto 80/20

In [42]:
# ETAPA 4.3 - ANÁLISE DE PARETO 80/20
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path
from matplotlib.ticker import FuncFormatter
from IPython.display import display

# Configurações
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.float_format", "{:,.4f}".format)

sns.set_theme(style="whitegrid")

plt.rcParams["figure.figsize"] = (12, 6)
plt.rcParams["axes.titlesize"] = 14
plt.rcParams["axes.labelsize"] = 11
plt.rcParams["xtick.labelsize"] = 10
plt.rcParams["ytick.labelsize"] = 10


# CARREGAMENTO DA BASE TRATADA
# ============================================================

caminho_base = Path("dados_empresa_tratado.csv")

if not caminho_base.exists():
    raise FileNotFoundError(
        "O arquivo 'dados_empresa_tratado.csv' não foi encontrado. "
        "Verifique se ele está na mesma pasta deste notebook."
    )

df = pd.read_csv(caminho_base)

df["data"] = pd.to_datetime(df["data"], errors="coerce")

In [43]:
# FUNÇÕES AUXILIARES
# ============================================================

def eixo_moeda(x, pos):
    if abs(x) >= 1_000_000:
        return f"R$ {x/1_000_000:.1f} mi"
    elif abs(x) >= 1_000:
        return f"R$ {x/1_000:.0f} mil"
    else:
        return f"R$ {x:.0f}"


def eixo_percentual(x, pos):
    return f"{x:.0f}%"

In [44]:
# FUNÇÃO GERAL PARA ANÁLISE DE PARETO
# ============================================================

def analise_pareto(base, dimensao, metrica, nome_metrica=None):
    """
    Realiza análise de Pareto 80/20 para uma dimensão e uma métrica.

    Parâmetros:
    - base: DataFrame com os dados.
    - dimensao: coluna categórica que será agrupada.
    - metrica: coluna numérica que será somada.
    - nome_metrica: nome opcional para exibição.

    Retorna:
    - DataFrame com total, participação percentual, acumulado e grupo Pareto.
    """

    if nome_metrica is None:
        nome_metrica = metrica

    tabela = base.groupby(dimensao).agg(
        valor_total=(metrica, "sum"),
        quantidade_registros=("id_venda", "count")
    ).reset_index()

    # Ordenar do maior para o menor valor
    tabela = tabela.sort_values("valor_total", ascending=False).reset_index(drop=True)

    # Criar ranking
    tabela.insert(0, "ranking", range(1, len(tabela) + 1))

    # Calcular participação percentual
    total_metrica = tabela["valor_total"].sum()

    tabela["participacao_%"] = (
        tabela["valor_total"] / total_metrica * 100
    )

    # Calcular participação acumulada
    tabela["participacao_acumulada_%"] = tabela["participacao_%"].cumsum()

    # Identificar o ponto em que o acumulado atinge ou ultrapassa 80%
    indice_limite_80 = tabela[tabela["participacao_acumulada_%"] >= 80].index.min()

    tabela["grupo_pareto_80"] = np.where(
        tabela.index <= indice_limite_80,
        "Sim",
        "Não"
    )

    tabela["dimensao_analisada"] = dimensao
    tabela["metrica_analisada"] = nome_metrica

    # Reordenar colunas
    tabela = tabela[
        [
            "ranking",
            "dimensao_analisada",
            dimensao,
            "metrica_analisada",
            "valor_total",
            "quantidade_registros",
            "participacao_%",
            "participacao_acumulada_%",
            "grupo_pareto_80"
        ]
    ]

    return tabela

In [45]:
# PARETO - PRODUTO VS. LUCRO TOTAL
# ============================================================

pareto_produto_lucro = analise_pareto(
    base=df,
    dimensao="produto",
    metrica="lucro",
    nome_metrica="Lucro Total"
)

pareto_produto_lucro

,ranking,dimensao_analisada,produto,metrica_analisada,valor_total,quantidade_registros,participacao_%,participacao_acumulada_%,grupo_pareto_80
0,1,produto,Monitor,Lucro Total,"448,537.8596",143,14.5544,14.5544,Sim
1,2,produto,Teclado,Lucro Total,"425,008.6724",115,13.7909,28.3453,Sim
2,3,produto,Impressora,Lucro Total,"419,170.2815",115,13.6015,41.9467,Sim
3,4,produto,Smartphone,Lucro Total,"402,535.9512",133,13.0617,55.0084,Sim
4,5,produto,Mouse,Lucro Total,"389,571.5908",133,12.6410,67.6495,Sim
5,6,produto,Notebook,Lucro Total,"386,693.2165",122,12.5476,80.1971,Sim
6,7,produto,Headset,Lucro Total,"310,612.3510",111,10.0789,90.2760,Não
7,8,produto,Tablet,Lucro Total,"299,674.7557",128,9.7240,100.0000,Não

A análise mostra que o lucro está relativamente distribuído entre os produtos, porque são necessários 6 produtos de 8 para atingir cerca de 80% do lucro.  
Isso indica que a empresa não depende de apenas um produto para gerar lucro. Porém, os produtos no grupo Pareto devem receber atenção estratégica, pois concentram a maior parte do resultado financeiro.

In [46]:
# PARETO - CATEGORIA VS. LUCRO TOTAL
# ============================================================

pareto_categoria_lucro = analise_pareto(
    base=df,
    dimensao="categoria",
    metrica="lucro",
    nome_metrica="Lucro Total"
)

pareto_categoria_lucro

,ranking,dimensao_analisada,categoria,metrica_analisada,valor_total,quantidade_registros,participacao_%,participacao_acumulada_%,grupo_pareto_80
0,1,categoria,Informática,Lucro Total,"1,502,208.4156",492,48.7444,48.7444,Sim
1,2,categoria,Periféricos,Lucro Total,"1,091,976.2666",346,35.4330,84.1775,Sim
2,3,categoria,Telefonia,Lucro Total,"399,791.5652",132,12.9726,97.1501,Não
3,4,categoria,Outros,Lucro Total,"87,828.4313",30,2.8499,100.0000,Não

Apenas 2 de 4 categorias concentram mais de 80% do lucro total. Isso indica que a empresa depende fortemente dessas categorias para gerar resultado.  
A empresa deve priorizar ações comerciais, estoque e campanhas principalmente em Informática e Periféricos, sem ignorar oportunidades de melhoria em categorias menores.

In [47]:
# PARETO - REGIÃO VS. LUCRO TOTAL
# ============================================================

pareto_regiao_lucro = analise_pareto(
    base=df,
    dimensao="regiao",
    metrica="lucro",
    nome_metrica="Lucro Total"
)

pareto_regiao_lucro

,ranking,dimensao_analisada,regiao,metrica_analisada,valor_total,quantidade_registros,participacao_%,participacao_acumulada_%,grupo_pareto_80
0,1,regiao,Sul,Lucro Total,"732,603.3099",209,23.7719,23.7719,Sim
1,2,regiao,Norte,Lucro Total,"689,213.0166",209,22.3639,46.1358,Sim
2,3,regiao,Centro-Oeste,Lucro Total,"586,749.5016",202,19.0392,65.1750,Sim
3,4,regiao,Nordeste,Lucro Total,"545,746.4773",181,17.7087,82.8837,Sim
4,5,regiao,Sudeste,Lucro Total,"527,492.3733",199,17.1163,100.0000,Não

A concentração regional do lucro não é tão forte. O lucro está relativamente distribuído entre as regiões.  
Mesmo assim, as regiões Sul, Norte, Centro-Oeste e Nordeste formam o grupo principal de contribuição para o lucro.

In [48]:
# PARETO - VENDEDOR VS. LUCRO TOTAL
# ============================================================

pareto_vendedor_lucro = analise_pareto(
    base=df,
    dimensao="vendedor",
    metrica="lucro",
    nome_metrica="Lucro Total"
)

pareto_vendedor_lucro

,ranking,dimensao_analisada,vendedor,metrica_analisada,valor_total,quantidade_registros,participacao_%,participacao_acumulada_%,grupo_pareto_80
0,1,vendedor,Vendedor_20,Lucro Total,"239,532.8195",49,7.7725,7.7725,Sim
1,2,vendedor,Vendedor_13,Lucro Total,"206,493.8594",60,6.7004,14.4729,Sim
2,3,vendedor,Vendedor_18,Lucro Total,"203,100.3786",53,6.5903,21.0632,Sim
3,4,vendedor,Vendedor_04,Lucro Total,"193,736.3400",55,6.2865,27.3497,Sim
4,5,vendedor,Vendedor_19,Lucro Total,"189,655.6283",50,6.1540,33.5037,Sim
5,6,vendedor,Vendedor_10,Lucro Total,"187,059.0811",63,6.0698,39.5735,Sim
6,7,vendedor,Vendedor_06,Lucro Total,"165,302.8134",50,5.3638,44.9373,Sim
7,8,vendedor,Vendedor_08,Lucro Total,"161,494.0416",46,5.2402,50.1776,Sim
8,9,vendedor,Vendedor_02,Lucro Total,"159,101.6319",48,5.1626,55.3402,Sim
9,10,vendedor,Vendedor_17,Lucro Total,"157,393.4398",50,5.1072,60.4474,Sim
10,11,vendedor,Vendedor_12,Lucro Total,"153,868.6462",60,4.9928,65.4402,Sim
11,12,vendedor,Vendedor_01,Lucro Total,"146,605.8213",44,4.7571,70.1973,Sim
12,13,vendedor,Vendedor_05,Lucro Total,"137,205.5400",49,4.4521,74.6494,Sim
13,14,vendedor,Vendedor_03,Lucro Total,"130,323.1076",50,4.2288,78.8782,Sim
14,15,vendedor,Vendedor_11,Lucro Total,"126,911.3290",48,4.1181,82.9963,Sim
15,16,vendedor,Vendedor_14,Lucro Total,"119,701.9180",41,3.8842,86.8805,Não
16,17,vendedor,Vendedor_07,Lucro Total,"115,382.0510",48,3.7440,90.6244,Não
17,18,vendedor,Vendedor_16,Lucro Total,"111,209.4803",43,3.6086,94.2330,Não
18,19,vendedor,Vendedor_09,Lucro Total,"95,398.9301",46,3.0956,97.3286,Não
19,20,vendedor,Vendedor_15,Lucro Total,"82,327.8216",47,2.6714,100.0000,Não

Neste caso, aproximadamente 15 dos 20 vendedores explicam cerca de 80% do lucro total.  
Isso mostra que o lucro da equipe comercial está relativamente distribuído, e não concentrado em poucos vendedores.

In [49]:
# PARETO - MARCA VS. LUCRO TOTAL
# ============================================================

pareto_marca_lucro = analise_pareto(
    base=df,
    dimensao="marca",
    metrica="lucro",
    nome_metrica="Lucro Total"
)

pareto_marca_lucro

,ranking,dimensao_analisada,marca,metrica_analisada,valor_total,quantidade_registros,participacao_%,participacao_acumulada_%,grupo_pareto_80
0,1,marca,Alpha,Lucro Total,"944,584.3441",255,30.6504,30.6504,Sim
1,2,marca,Beta,Lucro Total,"731,897.1498",250,23.7490,54.3993,Sim
2,3,marca,Gamma,Lucro Total,"726,318.2564",252,23.5680,77.9673,Sim
3,4,marca,Delta,Lucro Total,"679,004.9284",243,22.0327,100.0000,Sim

As marcas possuem contribuição relativamente equilibrada.  
A marca Alpha lidera a geração de lucro, mas não domina sozinha o resultado. Para atingir 80%, praticamente todas as marcas precisam ser consideradas.  
Isso indica que a empresa possui baixa dependência de uma única marca.

In [50]:
# PARETO - LINHA DE PRODUTO VS. LUCRO TOTAL
# ============================================================

pareto_linha_lucro = analise_pareto(
    base=df,
    dimensao="linha_produto",
    metrica="lucro",
    nome_metrica="Lucro Total"
)

pareto_linha_lucro

,ranking,dimensao_analisada,linha_produto,metrica_analisada,valor_total,quantidade_registros,participacao_%,participacao_acumulada_%,grupo_pareto_80
0,1,linha_produto,Econômico,Lucro Total,"1,052,581.7104",347,34.1547,34.1547,Sim
1,2,linha_produto,Premium,Lucro Total,"1,024,949.9764",330,33.2581,67.4128,Sim
2,3,linha_produto,Padrão,Lucro Total,"1,004,272.9919",323,32.5872,100.0000,Sim

As três linhas contribuem de forma bastante equilibrada para o lucro total.  
Não existe uma concentração forte em uma única linha. Isso mostra que a empresa consegue gerar lucro tanto em produtos econômicos quanto em produtos premium e padrão.

In [56]:
# PARETO - CLIENTE VS. LUCRO TOTAL
# ============================================================

pareto_cliente_lucro = analise_pareto(
    base=df,
    dimensao="cliente",
    metrica="lucro",
    nome_metrica="Lucro Total"
)

pareto_cliente_lucro

,ranking,dimensao_analisada,cliente,metrica_analisada,valor_total,quantidade_registros,participacao_%,participacao_acumulada_%,grupo_pareto_80
0,1,cliente,Cliente_027,Lucro Total,"51,569.9819",10,1.6734,1.6734,Sim
1,2,cliente,Cliente_092,Lucro Total,"49,858.0329",8,1.6178,3.2912,Sim
2,3,cliente,Cliente_163,Lucro Total,"45,361.2070",8,1.4719,4.7631,Sim
3,4,cliente,Cliente_095,Lucro Total,"42,719.3306",7,1.3862,6.1493,Sim
4,5,cliente,Cliente_144,Lucro Total,"42,483.6581",8,1.3785,7.5278,Sim
5,6,cliente,Cliente_017,Lucro Total,"41,843.4688",6,1.3578,8.8856,Sim
6,7,cliente,Cliente_024,Lucro Total,"40,736.2757",9,1.3218,10.2074,Sim
7,8,cliente,Cliente_041,Lucro Total,"39,215.1878",7,1.2725,11.4799,Sim
8,9,cliente,Cliente_179,Lucro Total,"38,882.2346",6,1.2617,12.7415,Sim
9,10,cliente,Cliente_033,Lucro Total,"38,873.6509",8,1.2614,14.0029,Sim
10,11,cliente,Cliente_148,Lucro Total,"38,780.0874",5,1.2584,15.2613,Sim
11,12,cliente,Cliente_141,Lucro Total,"38,164.6268",12,1.2384,16.4997,Sim
12,13,cliente,Cliente_083,Lucro Total,"37,001.1729",5,1.2006,17.7003,Sim
13,14,cliente,Cliente_110,Lucro Total,"36,223.7972",6,1.1754,18.8757,Sim
14,15,cliente,Cliente_018,Lucro Total,"35,680.1436",6,1.1578,20.0335,Sim
15,16,cliente,Cliente_118,Lucro Total,"35,197.2578",6,1.1421,21.1756,Sim
16,17,cliente,Cliente_090,Lucro Total,"34,705.9006",7,1.1262,22.3017,Sim
17,18,cliente,Cliente_085,Lucro Total,"33,386.4737",4,1.0833,23.3851,Sim
18,19,cliente,Cliente_011,Lucro Total,"32,828.1340",7,1.0652,24.4503,Sim
19,20,cliente,Cliente_057,Lucro Total,"32,780.7458",8,1.0637,25.5140,Sim
20,21,cliente,Cliente_120,Lucro Total,"32,481.6602",8,1.0540,26.5680,Sim
21,22,cliente,Cliente_151,Lucro Total,"31,297.7602",7,1.0156,27.5835,Sim
22,23,cliente,Cliente_188,Lucro Total,"31,265.3286",9,1.0145,28.5981,Sim
23,24,cliente,Cliente_051,Lucro Total,"31,237.9689",6,1.0136,29.6117,Sim
24,25,cliente,Cliente_149,Lucro Total,"30,848.0020",7,1.0010,30.6127,Sim
25,26,cliente,Cliente_185,Lucro Total,"30,643.8062",6,0.9943,31.6070,Sim
26,27,cliente,Cliente_045,Lucro Total,"30,641.3980",6,0.9943,32.6013,Sim
27,28,cliente,Cliente_088,Lucro Total,"30,342.2747",5,0.9846,33.5858,Sim
28,29,cliente,Cliente_109,Lucro Total,"29,994.9753",9,0.9733,34.5591,Sim
29,30,cliente,Cliente_061,Lucro Total,"29,350.5828",4,0.9524,35.5115,Sim
30,31,cliente,Cliente_032,Lucro Total,"28,055.8458",6,0.9104,36.4219,Sim
31,32,cliente,Cliente_097,Lucro Total,"27,595.9142",2,0.8954,37.3173,Sim
32,33,cliente,Cliente_123,Lucro Total,"27,140.4234",7,0.8807,38.1980,Sim
33,34,cliente,Cliente_127,Lucro Total,"26,467.9117",7,0.8588,39.0568,Sim
34,35,cliente,Cliente_129,Lucro Total,"25,507.6304",8,0.8277,39.8845,Sim
35,36,cliente,Cliente_036,Lucro Total,"25,318.0119",9,0.8215,40.7060,Sim
36,37,cliente,Cliente_169,Lucro Total,"25,164.6648",5,0.8166,41.5226,Sim
37,38,cliente,Cliente_106,Lucro Total,"24,395.9347",6,0.7916,42.3142,Sim
38,39,cliente,Cliente_062,Lucro Total,"24,127.5779",7,0.7829,43.0971,Sim
39,40,cliente,Cliente_111,Lucro Total,"23,771.3262",4,0.7713,43.8685,Sim
40,41,cliente,Cliente_052,Lucro Total,"23,670.4424",8,0.7681,44.6365,Sim
41,42,cliente,Cliente_133,Lucro Total,"23,465.1182",7,0.7614,45.3979,Sim
42,43,cliente,Cliente_180,Lucro Total,"23,200.2132",3,0.7528,46.1508,Sim
43,44,cliente,Cliente_137,Lucro Total,"22,766.2664",4,0.7387,46.8895,Sim
44,45,cliente,Cliente_170,Lucro Total,"22,669.0483",5,0.7356,47.6251,Sim
45,46,cliente,Cliente_140,Lucro Total,"22,633.4254",6,0.7344,48.3595,Sim
46,47,cliente,Cliente_189,Lucro Total,"22,604.5955",5,0.7335,49.0930,Sim
47,48,cliente,Cliente_160,Lucro Total,"22,456.6795",7,0.7287,49.8217,Sim
48,49,cliente,Cliente_184,Lucro Total,"22,397.3139",3,0.7268,50.5484,Sim
49,50,cliente,Cliente_040,Lucro Total,"22,378.1192",7,0.7261,51.2746,Sim
50,51,cliente,Cliente_168,Lucro Total,"22,266.5937",7,0.7225,51.9971,Sim
51,52,cliente,Cliente_043,Lucro Total,"22,022.6801",7,0.7146,52.7117,Sim
52,53,cliente,Cliente_054,Lucro Total,"21,907.5320",3,0.7109,53.4225,Sim
53,54,cliente,Cliente_071,Lucro Total,"21,740.7878",7,0.7055,54.1280,Sim
54,55,cliente,Cliente_167,Lucro Total,"21,572.2505",6,0.7000,54.8280,Sim
55,56,cliente,Cliente_034,Lucro Total,"21,374.5273",5,0.6936,55.5216,Sim
56,57,cliente,Cliente_138,Lucro Total,"21,294.7728",8,0.6910,56.2125,Sim
57,58,cliente,Cliente_124,Lucro Total,"20,984.6400",4,0.6809,56.8935,Sim
58,59,cliente,Cliente_080,Lucro Total,"20,945.7406",7,0.6797,57.5731,Sim
59,60,cliente,Cliente_172,Lucro Total,"20,442.0543",5,0.6633,58.2364,Sim
60,61,cliente,Cliente_053,Lucro Total,"20,377.3008",6,0.6612,58.8976,Sim
61,62,cliente,Cliente_065,Lucro Total,"19,992.6588",6,0.6487,59.5464,Sim
62,63,cliente,Cliente_108,Lucro Total,"19,208.4786",3,0.6233,60.1697,Sim
63,64,cliente,Cliente_029,Lucro Total,"18,926.1510",5,0.6141,60.7838,Sim
64,65,cliente,Cliente_195,Lucro Total,"18,893.0812",6,0.6131,61.3968,Sim
65,66,cliente,Cliente_005,Lucro Total,"18,312.3470",8,0.5942,61.9911,Sim
66,67,cliente,Cliente_067,Lucro Total,"18,282.7678",5,0.5932,62.5843,Sim
67,68,cliente,Cliente_192,Lucro Total,"17,849.2119",5,0.5792,63.1635,Sim
68,69,cliente,Cliente_048,Lucro Total,"17,698.1516",9,0.5743,63.7378,Sim
69,70,cliente,Cliente_075,Lucro Total,"17,687.5400",4,0.5739,64.3117,Sim
70,71,cliente,Cliente_016,Lucro Total,"17,685.4002",9,0.5739,64.8856,Sim
71,72,cliente,Cliente_091,Lucro Total,"17,583.3745",5,0.5706,65.4561,Sim
72,73,cliente,Cliente_035,Lucro Total,"17,261.1534",8,0.5601,66.0162,Sim
73,74,cliente,Cliente_117,Lucro Total,"16,961.4084",6,0.5504,66.5666,Sim
74,75,cliente,Cliente_093,Lucro Total,"16,835.0917",6,0.5463,67.1129,Sim
75,76,cliente,Cliente_143,Lucro Total,"16,809.5760",6,0.5454,67.6583,Sim
76,77,cliente,Cliente_021,Lucro Total,"16,766.8913",4,0.5441,68.2024,Sim
77,78,cliente,Cliente_125,Lucro Total,"16,748.1600",4,0.5435,68.7458,Sim
78,79,cliente,Cliente_099,Lucro Total,"16,649.4951",6,0.5403,69.2861,Sim
79,80,cliente,Cliente_119,Lucro Total,"16,372.8526",6,0.5313,69.8173,Sim
80,81,cliente,Cliente_147,Lucro Total,"16,358.8858",6,0.5308,70.3482,Sim
81,82,cliente,Cliente_173,Lucro Total,"16,027.8564",6,0.5201,70.8682,Sim
82,83,cliente,Cliente_158,Lucro Total,"15,949.2553",4,0.5175,71.3858,Sim
83,84,cliente,Cliente_154,Lucro Total,"15,797.3946",8,0.5126,71.8984,Sim
84,85,cliente,Cliente_175,Lucro Total,"15,721.3999",8,0.5101,72.4085,Sim
85,86,cliente,Cliente_077,Lucro Total,"15,650.2868",5,0.5078,72.9163,Sim
86,87,cliente,Cliente_100,Lucro Total,"15,169.6490",2,0.4922,73.4086,Sim
87,88,cliente,Cliente_178,Lucro Total,"14,912.9824",6,0.4839,73.8925,Sim
88,89,cliente,Cliente_008,Lucro Total,"14,848.2687",4,0.4818,74.3743,Sim
89,90,cliente,Cliente_155,Lucro Total,"14,817.9607",5,0.4808,74.8551,Sim
90,91,cliente,Cliente_128,Lucro Total,"14,448.4916",7,0.4688,75.3239,Sim
91,92,cliente,Cliente_084,Lucro Total,"14,432.1264",5,0.4683,75.7922,Sim
92,93,cliente,Cliente_134,Lucro Total,"14,362.2446",4,0.4660,76.2583,Sim
93,94,cliente,Cliente_174,Lucro Total,"13,801.3653",5,0.4478,76.7061,Sim
94,95,cliente,Cliente_098,Lucro Total,"13,800.4979",6,0.4478,77.1539,Sim
95,96,cliente,Cliente_126,Lucro Total,"13,603.9426",6,0.4414,77.5953,Sim
96,97,cliente,Cliente_113,Lucro Total,"13,372.3007",4,0.4339,78.0293,Sim
97,98,cliente,Cliente_150,Lucro Total,"13,061.0370",7,0.4238,78.4531,Sim
98,99,cliente,Cliente_122,Lucro Total,"12,749.1861",3,0.4137,78.8668,Sim
99,100,cliente,Cliente_020,Lucro Total,"12,719.8898",5,0.4127,79.2795,Sim
100,101,cliente,Cliente_176,Lucro Total,"12,612.3153",7,0.4093,79.6887,Sim
101,102,cliente,Cliente_181,Lucro Total,"12,537.5798",4,0.4068,80.0956,Sim
102,103,cliente,Cliente_060,Lucro Total,"12,501.9828",7,0.4057,80.5012,Não
103,104,cliente,Cliente_107,Lucro Total,"12,428.9206",4,0.4033,80.9045,Não
104,105,cliente,Cliente_081,Lucro Total,"12,383.9340",6,0.4018,81.3064,Não
105,106,cliente,Cliente_165,Lucro Total,"12,317.8602",4,0.3997,81.7061,Não
106,107,cliente,Cliente_130,Lucro Total,"12,306.2668",4,0.3993,82.1054,Não
107,108,cliente,Cliente_019,Lucro Total,"12,219.5009",6,0.3965,82.5019,Não
108,109,cliente,Cliente_002,Lucro Total,"12,051.4519",4,0.3911,82.8930,Não
109,110,cliente,Cliente_161,Lucro Total,"11,574.0182",2,0.3756,83.2685,Não
110,111,cliente,Cliente_115,Lucro Total,"11,525.6816",9,0.3740,83.6425,Não
111,112,cliente,Cliente_058,Lucro Total,"11,491.9382",3,0.3729,84.0154,Não
112,113,cliente,Cliente_139,Lucro Total,"11,415.4708",7,0.3704,84.3858,Não
113,114,cliente,Cliente_153,Lucro Total,"11,408.9370",2,0.3702,84.7560,Não
114,115,cliente,Cliente_131,Lucro Total,"11,345.2752",3,0.3681,85.1242,Não
115,116,cliente,Cliente_187,Lucro Total,"11,240.6756",2,0.3647,85.4889,Não
116,117,cliente,Cliente_142,Lucro Total,"10,638.5690",5,0.3452,85.8341,Não
117,118,cliente,Cliente_001,Lucro Total,"10,638.2257",6,0.3452,86.1793,Não
118,119,cliente,Cliente_136,Lucro Total,"10,488.3732",5,0.3403,86.5196,Não
119,120,cliente,Cliente_022,Lucro Total,"10,452.8217",6,0.3392,86.8588,Não
120,121,cliente,Cliente_121,Lucro Total,"10,380.0096",9,0.3368,87.1956,Não
121,122,cliente,Cliente_162,Lucro Total,"10,244.2371",4,0.3324,87.5280,Não
122,123,cliente,Cliente_104,Lucro Total,"10,148.1293",7,0.3293,87.8573,Não
123,124,cliente,Cliente_102,Lucro Total,"10,006.4674",4,0.3247,88.1820,Não
124,125,cliente,Cliente_164,Lucro Total,"9,655.0011",4,0.3133,88.4953,Não
125,126,cliente,Cliente_066,Lucro Total,"9,554.4856",6,0.3100,88.8053,Não
126,127,cliente,Cliente_069,Lucro Total,"9,505.6306",3,0.3084,89.1138,Não
127,128,cliente,Cliente_116,Lucro Total,"9,407.1116",4,0.3052,89.4190,Não
128,129,cliente,Cliente_094,Lucro Total,"9,399.8588",3,0.3050,89.7241,Não
129,130,cliente,Cliente_193,Lucro Total,"9,287.1088",4,0.3014,90.0254,Não
130,131,cliente,Cliente_078,Lucro Total,"9,112.4664",3,0.2957,90.3211,Não
131,132,cliente,Cliente_031,Lucro Total,"9,015.9520",4,0.2926,90.6136,Não
132,133,cliente,Cliente_028,Lucro Total,"8,940.9318",5,0.2901,90.9038,Não
133,134,cliente,Cliente_198,Lucro Total,"8,800.4946",3,0.2856,91.1893,Não
134,135,cliente,Cliente_145,Lucro Total,"8,680.6008",2,0.2817,91.4710,Não
135,136,cliente,Cliente_152,Lucro Total,"8,675.3547",2,0.2815,91.7525,Não
136,137,cliente,Cliente_012,Lucro Total,"8,517.3306",5,0.2764,92.0289,Não
137,138,cliente,Cliente_049,Lucro Total,"8,486.5070",6,0.2754,92.3043,Não
138,139,cliente,Cliente_047,Lucro Total,"8,425.7155",4,0.2734,92.5777,Não
139,140,cliente,Cliente_182,Lucro Total,"8,279.5971",6,0.2687,92.8463,Não
140,141,cliente,Cliente_063,Lucro Total,"8,227.2648",3,0.2670,93.1133,Não
141,142,cliente,Cliente_010,Lucro Total,"8,026.9722",2,0.2605,93.3737,Não
142,143,cliente,Cliente_064,Lucro Total,"7,893.1563",7,0.2561,93.6299,Não
143,144,cliente,Cliente_114,Lucro Total,"7,557.8570",4,0.2452,93.8751,Não
144,145,cliente,Cliente_056,Lucro Total,"7,462.5128",3,0.2421,94.1173,Não
145,146,cliente,Cliente_037,Lucro Total,"7,430.6976",4,0.2411,94.3584,Não
146,147,cliente,Cliente_171,Lucro Total,"7,356.7282",4,0.2387,94.5971,Não
147,148,cliente,Cliente_132,Lucro Total,"7,234.8459",5,0.2348,94.8318,Não
148,149,cliente,Cliente_194,Lucro Total,"7,105.4200",4,0.2306,95.0624,Não
149,150,cliente,Cliente_086,Lucro Total,"6,874.6772",4,0.2231,95.2855,Não
150,151,cliente,Cliente_196,Lucro Total,"6,671.1661",6,0.2165,95.5019,Não
151,152,cliente,Cliente_156,Lucro Total,"6,621.3822",4,0.2149,95.7168,Não
152,153,cliente,Cliente_042,Lucro Total,"6,557.3554",4,0.2128,95.9296,Não
153,154,cliente,Cliente_079,Lucro Total,"6,482.8709",3,0.2104,96.1399,Não
154,155,cliente,Cliente_013,Lucro Total,"6,474.6728",6,0.2101,96.3500,Não
155,156,cliente,Cliente_055,Lucro Total,"6,335.3016",3,0.2056,96.5556,Não
156,157,cliente,Cliente_087,Lucro Total,"6,245.4495",8,0.2027,96.7583,Não
157,158,cliente,Cliente_112,Lucro Total,"6,216.0455",5,0.2017,96.9600,Não
158,159,cliente,Cliente_009,Lucro Total,"6,175.3103",5,0.2004,97.1603,Não
159,160,cliente,Cliente_046,Lucro Total,"6,171.9388",6,0.2003,97.3606,Não
160,161,cliente,Cliente_070,Lucro Total,"6,093.5248",4,0.1977,97.5583,Não
161,162,cliente,Cliente_146,Lucro Total,"6,062.0331",4,0.1967,97.7550,Não
162,163,cliente,Cliente_096,Lucro Total,"6,031.0749",5,0.1957,97.9507,Não
163,164,cliente,Cliente_025,Lucro Total,"5,266.8467",4,0.1709,98.1216,Não
164,165,cliente,Cliente_023,Lucro Total,"5,123.6303",4,0.1663,98.2879,Não
165,166,cliente,Cliente_014,Lucro Total,"4,876.9091",6,0.1582,98.4461,Não
166,167,cliente,Cliente_186,Lucro Total,"4,800.9723",4,0.1558,98.6019,Não
167,168,cliente,Cliente_003,Lucro Total,"4,694.9745",4,0.1523,98.7543,Não
168,169,cliente,Cliente_135,Lucro Total,"4,581.4830",3,0.1487,98.9029,Não
169,170,cliente,Cliente_103,Lucro Total,"4,415.9994",4,0.1433,99.0462,Não
170,171,cliente,Cliente_038,Lucro Total,"4,410.5535",3,0.1431,99.1893,Não
171,172,cliente,Cliente_030,Lucro Total,"3,687.9392",3,0.1197,99.3090,Não
172,173,cliente,Cliente_089,Lucro Total,"3,271.3643",6,0.1062,99.4152,Não
173,174,cliente,Cliente_073,Lucro Total,"3,160.9600",1,0.1026,99.5177,Não
174,175,cliente,Cliente_007,Lucro Total,"3,110.8786",3,0.1009,99.6187,Não
175,176,cliente,Cliente_026,Lucro Total,"3,073.9296",2,0.0997,99.7184,Não
176,177,cliente,Cliente_190,Lucro Total,"2,376.4611",4,0.0771,99.7955,Não
177,178,cliente,Cliente_059,Lucro Total,"2,175.5830",2,0.0706,99.8661,Não
178,179,cliente,Cliente_015,Lucro Total,"2,098.1344",1,0.0681,99.9342,Não
179,180,cliente,Cliente_074,Lucro Total,"1,914.2161",3,0.0621,99.9963,Não
180,181,cliente,Cliente_200,Lucro Total,"1,862.0800",1,0.0604,100.0567,Não
181,182,cliente,Cliente_191,Lucro Total,"1,641.5562",1,0.0533,100.1100,Não
182,183,cliente,Cliente_068,Lucro Total,"1,598.1516",4,0.0519,100.1619,Não
183,184,cliente,Cliente_157,Lucro Total,"1,570.8864",1,0.0510,100.2128,Não
184,185,cliente,Cliente_183,Lucro Total,"1,504.0204",5,0.0488,100.2616,Não
185,186,cliente,Cliente_004,Lucro Total,"1,311.9142",3,0.0426,100.3042,Não
186,187,cliente,Cliente_199,Lucro Total,906.6824,3,0.0294,100.3336,Não
187,188,cliente,Cliente_105,Lucro Total,889.3697,2,0.0289,100.3625,Não
188,189,cliente,Cliente_076,Lucro Total,775.6504,1,0.0252,100.3877,Não
189,190,cliente,Cliente_101,Lucro Total,362.5947,3,0.0118,100.3994,Não
190,191,cliente,Cliente_006,Lucro Total,37.2115,2,0.0012,100.4006,Não
191,192,cliente,Cliente_072,Lucro Total,12.4388,1,0.0004,100.4010,Não
192,193,cliente,Cliente_197,Lucro Total,-59.1026,6,-0.0019,100.3991,Não
193,194,cliente,Cliente_166,Lucro Total,-177.5946,2,-0.0058,100.3934,Não
194,195,cliente,Cliente_039,Lucro Total,-406.5160,2,-0.0132,100.3802,Não
195,196,cliente,Cliente_177,Lucro Total,-962.5275,1,-0.0312,100.3489,Não
196,197,cliente,Cliente_050,Lucro Total,"-1,281.7701",4,-0.0416,100.3073,Não
197,198,cliente,Cliente_082,Lucro Total,"-2,262.8751",3,-0.0734,100.2339,Não
198,199,cliente,Cliente_159,Lucro Total,"-7,208.6542",3,-0.2339,100.0000,Não

In [51]:
# PARETO - CLIENTE VS. RECEITA TOTAL
# ============================================================

pareto_cliente_receita = analise_pareto(
    base=df,
    dimensao="cliente",
    metrica="receita",
    nome_metrica="Receita Total"
)

pareto_cliente_receita

,ranking,dimensao_analisada,cliente,metrica_analisada,valor_total,quantidade_registros,participacao_%,participacao_acumulada_%,grupo_pareto_80
0,1,cliente,Cliente_141,Receita Total,"230,739.4268",12,1.5184,1.5184,Sim
1,2,cliente,Cliente_163,Receita Total,"203,101.4770",8,1.3365,2.8549,Sim
2,3,cliente,Cliente_027,Receita Total,"189,974.1819",10,1.2501,4.1051,Sim
3,4,cliente,Cliente_057,Receita Total,"187,579.4158",8,1.2344,5.3395,Sim
4,5,cliente,Cliente_041,Receita Total,"187,398.9478",7,1.2332,6.5727,Sim
5,6,cliente,Cliente_144,Receita Total,"179,184.7981",8,1.1791,7.7518,Sim
6,7,cliente,Cliente_092,Receita Total,"177,111.1229",8,1.1655,8.9173,Sim
7,8,cliente,Cliente_017,Receita Total,"171,863.6188",6,1.1310,10.0483,Sim
8,9,cliente,Cliente_118,Receita Total,"170,630.9178",6,1.1229,11.1712,Sim
9,10,cliente,Cliente_024,Receita Total,"167,628.3157",9,1.1031,12.2743,Sim
10,11,cliente,Cliente_115,Receita Total,"167,588.1416",9,1.1028,13.3771,Sim
11,12,cliente,Cliente_093,Receita Total,"161,915.0617",6,1.0655,14.4426,Sim
12,13,cliente,Cliente_120,Receita Total,"161,262.0202",8,1.0612,15.5038,Sim
13,14,cliente,Cliente_095,Receita Total,"159,413.4606",7,1.0490,16.5529,Sim
14,15,cliente,Cliente_071,Receita Total,"151,605.7978",7,0.9977,17.5505,Sim
15,16,cliente,Cliente_129,Receita Total,"150,659.1304",8,0.9914,18.5419,Sim
16,17,cliente,Cliente_109,Receita Total,"148,082.2553",9,0.9745,19.5164,Sim
17,18,cliente,Cliente_033,Receita Total,"138,310.4109",8,0.9102,20.4266,Sim
18,19,cliente,Cliente_036,Receita Total,"133,530.5819",9,0.8787,21.3053,Sim
19,20,cliente,Cliente_077,Receita Total,"130,923.1768",5,0.8616,22.1669,Sim
20,21,cliente,Cliente_083,Receita Total,"130,835.6129",5,0.8610,23.0278,Sim
21,22,cliente,Cliente_011,Receita Total,"129,779.5340",7,0.8540,23.8819,Sim
22,23,cliente,Cliente_051,Receita Total,"127,964.1389",6,0.8421,24.7240,Sim
23,24,cliente,Cliente_018,Receita Total,"127,598.2136",6,0.8397,25.5636,Sim
24,25,cliente,Cliente_148,Receita Total,"125,120.4174",5,0.8234,26.3870,Sim
25,26,cliente,Cliente_053,Receita Total,"124,438.2508",6,0.8189,27.2059,Sim
26,27,cliente,Cliente_149,Receita Total,"123,203.5620",7,0.8108,28.0166,Sim
27,28,cliente,Cliente_160,Receita Total,"119,541.2695",7,0.7867,28.8033,Sim
28,29,cliente,Cliente_045,Receita Total,"119,148.4080",6,0.7841,29.5874,Sim
29,30,cliente,Cliente_090,Receita Total,"118,955.1506",7,0.7828,30.3702,Sim
30,31,cliente,Cliente_040,Receita Total,"116,393.6392",7,0.7659,31.1361,Sim
31,32,cliente,Cliente_052,Receita Total,"115,906.7424",8,0.7627,31.8989,Sim
32,33,cliente,Cliente_061,Receita Total,"115,262.5028",4,0.7585,32.6574,Sim
33,34,cliente,Cliente_121,Receita Total,"114,957.7696",9,0.7565,33.4138,Sim
34,35,cliente,Cliente_179,Receita Total,"113,542.8046",6,0.7472,34.1610,Sim
35,36,cliente,Cliente_188,Receita Total,"113,505.4386",9,0.7469,34.9080,Sim
36,37,cliente,Cliente_189,Receita Total,"113,172.6555",5,0.7447,35.6527,Sim
37,38,cliente,Cliente_168,Receita Total,"112,817.8237",7,0.7424,36.3951,Sim
38,39,cliente,Cliente_134,Receita Total,"111,779.5646",4,0.7356,37.1307,Sim
39,40,cliente,Cliente_110,Receita Total,"110,354.9572",6,0.7262,37.8569,Sim
40,41,cliente,Cliente_016,Receita Total,"110,228.0802",9,0.7254,38.5823,Sim
41,42,cliente,Cliente_032,Receita Total,"106,369.9858",6,0.7000,39.2823,Sim
42,43,cliente,Cliente_014,Receita Total,"106,242.6191",6,0.6991,39.9814,Sim
43,44,cliente,Cliente_123,Receita Total,"106,115.0734",7,0.6983,40.6797,Sim
44,45,cliente,Cliente_088,Receita Total,"104,047.6147",5,0.6847,41.3644,Sim
45,46,cliente,Cliente_116,Receita Total,"102,612.4616",4,0.6753,42.0397,Sim
46,47,cliente,Cliente_062,Receita Total,"101,989.3479",7,0.6712,42.7108,Sim
47,48,cliente,Cliente_172,Receita Total,"101,852.6243",5,0.6703,43.3811,Sim
48,49,cliente,Cliente_005,Receita Total,"101,541.5970",8,0.6682,44.0493,Sim
49,50,cliente,Cliente_106,Receita Total,"101,201.9147",6,0.6660,44.7152,Sim
50,51,cliente,Cliente_067,Receita Total,"100,758.7778",5,0.6631,45.3783,Sim
51,52,cliente,Cliente_111,Receita Total,"100,331.5362",4,0.6602,46.0385,Sim
52,53,cliente,Cliente_035,Receita Total,"100,261.5734",8,0.6598,46.6983,Sim
53,54,cliente,Cliente_001,Receita Total,"99,475.2457",6,0.6546,47.3529,Sim
54,55,cliente,Cliente_185,Receita Total,"99,023.8962",6,0.6516,48.0046,Sim
55,56,cliente,Cliente_096,Receita Total,"98,724.8449",5,0.6497,48.6543,Sim
56,57,cliente,Cliente_139,Receita Total,"97,435.3908",7,0.6412,49.2954,Sim
57,58,cliente,Cliente_098,Receita Total,"94,527.4679",6,0.6221,49.9175,Sim
58,59,cliente,Cliente_104,Receita Total,"94,437.8193",7,0.6215,50.5389,Sim
59,60,cliente,Cliente_150,Receita Total,"93,694.5770",7,0.6166,51.1555,Sim
60,61,cliente,Cliente_133,Receita Total,"93,674.7082",7,0.6164,51.7720,Sim
61,62,cliente,Cliente_117,Receita Total,"91,623.2184",6,0.6029,52.3749,Sim
62,63,cliente,Cliente_087,Receita Total,"88,724.3095",8,0.5839,52.9588,Sim
63,64,cliente,Cliente_127,Receita Total,"88,363.4117",7,0.5815,53.5402,Sim
64,65,cliente,Cliente_085,Receita Total,"88,344.6537",4,0.5814,54.1216,Sim
65,66,cliente,Cliente_147,Receita Total,"88,179.2158",6,0.5803,54.7019,Sim
66,67,cliente,Cliente_008,Receita Total,"88,177.9587",4,0.5803,55.2821,Sim
67,68,cliente,Cliente_154,Receita Total,"87,264.0446",8,0.5743,55.8564,Sim
68,69,cliente,Cliente_048,Receita Total,"87,135.5516",9,0.5734,56.4298,Sim
69,70,cliente,Cliente_065,Receita Total,"86,117.3388",6,0.5667,56.9965,Sim
70,71,cliente,Cliente_170,Receita Total,"84,229.3583",5,0.5543,57.5508,Sim
71,72,cliente,Cliente_183,Receita Total,"83,237.1004",5,0.5478,58.0985,Sim
72,73,cliente,Cliente_047,Receita Total,"83,114.8655",4,0.5469,58.6455,Sim
73,74,cliente,Cliente_049,Receita Total,"83,039.5370",6,0.5465,59.1919,Sim
74,75,cliente,Cliente_169,Receita Total,"83,008.4048",5,0.5462,59.7382,Sim
75,76,cliente,Cliente_124,Receita Total,"82,369.3200",4,0.5420,60.2802,Sim
76,77,cliente,Cliente_181,Receita Total,"82,348.4698",4,0.5419,60.8221,Sim
77,78,cliente,Cliente_151,Receita Total,"82,048.7002",7,0.5399,61.3621,Sim
78,79,cliente,Cliente_013,Receita Total,"81,355.5328",6,0.5354,61.8974,Sim
79,80,cliente,Cliente_140,Receita Total,"80,983.9454",6,0.5329,62.4304,Sim
80,81,cliente,Cliente_155,Receita Total,"80,183.7807",5,0.5277,62.9580,Sim
81,82,cliente,Cliente_159,Receita Total,"79,972.4358",3,0.5263,63.4843,Sim
82,83,cliente,Cliente_080,Receita Total,"79,812.0906",7,0.5252,64.0095,Sim
83,84,cliente,Cliente_099,Receita Total,"78,861.3051",6,0.5190,64.5285,Sim
84,85,cliente,Cliente_043,Receita Total,"78,557.9301",7,0.5170,65.0454,Sim
85,86,cliente,Cliente_107,Receita Total,"77,787.0206",4,0.5119,65.5573,Sim
86,87,cliente,Cliente_142,Receita Total,"77,512.9390",5,0.5101,66.0674,Sim
87,88,cliente,Cliente_034,Receita Total,"77,494.1573",5,0.5100,66.5774,Sim
88,89,cliente,Cliente_126,Receita Total,"77,477.5626",6,0.5099,67.0872,Sim
89,90,cliente,Cliente_078,Receita Total,"76,146.6264",3,0.5011,67.5883,Sim
90,91,cliente,Cliente_195,Receita Total,"75,687.0012",6,0.4981,68.0864,Sim
91,92,cliente,Cliente_023,Receita Total,"73,946.1803",4,0.4866,68.5730,Sim
92,93,cliente,Cliente_020,Receita Total,"73,924.8298",5,0.4865,69.0595,Sim
93,94,cliente,Cliente_138,Receita Total,"73,910.1928",8,0.4864,69.5458,Sim
94,95,cliente,Cliente_161,Receita Total,"73,870.6482",2,0.4861,70.0319,Sim
95,96,cliente,Cliente_112,Receita Total,"71,791.8255",5,0.4724,70.5044,Sim
96,97,cliente,Cliente_125,Receita Total,"71,628.4000",4,0.4714,70.9757,Sim
97,98,cliente,Cliente_089,Receita Total,"71,355.7743",6,0.4696,71.4453,Sim
98,99,cliente,Cliente_153,Receita Total,"71,293.7070",2,0.4692,71.9145,Sim
99,100,cliente,Cliente_122,Receita Total,"70,753.9761",3,0.4656,72.3801,Sim
100,101,cliente,Cliente_066,Receita Total,"70,468.0656",6,0.4637,72.8438,Sim
101,102,cliente,Cliente_184,Receita Total,"70,217.2839",3,0.4621,73.3059,Sim
102,103,cliente,Cliente_019,Receita Total,"70,066.7009",6,0.4611,73.7670,Sim
103,104,cliente,Cliente_180,Receita Total,"69,787.9532",3,0.4592,74.2262,Sim
104,105,cliente,Cliente_119,Receita Total,"69,746.9726",6,0.4590,74.6852,Sim
105,106,cliente,Cliente_060,Receita Total,"68,560.6428",7,0.4512,75.1364,Sim
106,107,cliente,Cliente_021,Receita Total,"68,342.4313",4,0.4497,75.5861,Sim
107,108,cliente,Cliente_097,Receita Total,"67,800.9042",2,0.4462,76.0323,Sim
108,109,cliente,Cliente_128,Receita Total,"67,245.6616",7,0.4425,76.4748,Sim
109,110,cliente,Cliente_158,Receita Total,"66,805.3653",4,0.4396,76.9144,Sim
110,111,cliente,Cliente_100,Receita Total,"66,370.1390",2,0.4368,77.3512,Sim
111,112,cliente,Cliente_012,Receita Total,"66,366.5006",5,0.4367,77.7879,Sim
112,113,cliente,Cliente_086,Receita Total,"66,314.5872",4,0.4364,78.2243,Sim
113,114,cliente,Cliente_029,Receita Total,"66,166.5010",5,0.4354,78.6597,Sim
114,115,cliente,Cliente_037,Receita Total,"66,137.7276",4,0.4352,79.0949,Sim
115,116,cliente,Cliente_054,Receita Total,"65,560.4520",3,0.4314,79.5264,Sim
116,117,cliente,Cliente_002,Receita Total,"65,329.1119",4,0.4299,79.9563,Sim
117,118,cliente,Cliente_197,Receita Total,"65,242.5874",6,0.4293,80.3856,Sim
118,119,cliente,Cliente_175,Receita Total,"64,630.7999",8,0.4253,80.8109,Não
119,120,cliente,Cliente_046,Receita Total,"63,980.8688",6,0.4210,81.2319,Não
120,121,cliente,Cliente_167,Receita Total,"63,087.6805",6,0.4152,81.6471,Não
121,122,cliente,Cliente_091,Receita Total,"62,976.0845",5,0.4144,82.0615,Não
122,123,cliente,Cliente_075,Receita Total,"61,131.9300",4,0.4023,82.4638,Não
123,124,cliente,Cliente_114,Receita Total,"61,002.8070",4,0.4014,82.8652,Não
124,125,cliente,Cliente_031,Receita Total,"60,708.0720",4,0.3995,83.2647,Não
125,126,cliente,Cliente_137,Receita Total,"60,345.0964",4,0.3971,83.6619,Não
126,127,cliente,Cliente_173,Receita Total,"59,576.5864",6,0.3921,84.0539,Não
127,128,cliente,Cliente_176,Receita Total,"59,406.3953",7,0.3909,84.4448,Não
128,129,cliente,Cliente_162,Receita Total,"59,283.5471",4,0.3901,84.8350,Não
129,130,cliente,Cliente_193,Receita Total,"59,160.4388",4,0.3893,85.2243,Não
130,131,cliente,Cliente_164,Receita Total,"58,372.6311",4,0.3841,85.6084,Não
131,132,cliente,Cliente_094,Receita Total,"57,202.2488",3,0.3764,85.9848,Não
132,133,cliente,Cliente_178,Receita Total,"56,994.9324",6,0.3751,86.3599,Não
133,134,cliente,Cliente_192,Receita Total,"56,819.3019",5,0.3739,86.7338,Não
134,135,cliente,Cliente_028,Receita Total,"56,107.2518",5,0.3692,87.1030,Não
135,136,cliente,Cliente_082,Receita Total,"56,081.1949",3,0.3690,87.4721,Não
136,137,cliente,Cliente_081,Receita Total,"54,594.7740",6,0.3593,87.8313,Não
137,138,cliente,Cliente_187,Receita Total,"54,559.5356",2,0.3590,88.1904,Não
138,139,cliente,Cliente_064,Receita Total,"53,604.0063",7,0.3527,88.5431,Não
139,140,cliente,Cliente_025,Receita Total,"51,490.6767",4,0.3388,88.8820,Não
140,141,cliente,Cliente_186,Receita Total,"51,327.4323",4,0.3378,89.2197,Não
141,142,cliente,Cliente_174,Receita Total,"50,655.5053",5,0.3333,89.5531,Não
142,143,cliente,Cliente_009,Receita Total,"50,518.4003",5,0.3324,89.8855,Não
143,144,cliente,Cliente_165,Receita Total,"50,133.1002",4,0.3299,90.2154,Não
144,145,cliente,Cliente_143,Receita Total,"50,108.9960",6,0.3297,90.5452,Não
145,146,cliente,Cliente_136,Receita Total,"47,918.7932",5,0.3153,90.8605,Não
146,147,cliente,Cliente_058,Receita Total,"47,190.7482",3,0.3105,91.1710,Não
147,148,cliente,Cliente_113,Receita Total,"46,792.6707",4,0.3079,91.4790,Não
148,149,cliente,Cliente_108,Receita Total,"46,118.5786",3,0.3035,91.7825,Não
149,150,cliente,Cliente_194,Receita Total,"46,010.1200",4,0.3028,92.0852,Não
150,151,cliente,Cliente_084,Receita Total,"45,289.5064",5,0.2980,92.3833,Não
151,152,cliente,Cliente_171,Receita Total,"42,656.4982",4,0.2807,92.6640,Não
152,153,cliente,Cliente_198,Receita Total,"41,511.6546",3,0.2732,92.9372,Não
153,154,cliente,Cliente_102,Receita Total,"41,307.6474",4,0.2718,93.2090,Não
154,155,cliente,Cliente_059,Receita Total,"39,689.3430",2,0.2612,93.4702,Não
155,156,cliente,Cliente_135,Receita Total,"39,212.8330",3,0.2580,93.7282,Não
156,157,cliente,Cliente_199,Receita Total,"38,997.3624",3,0.2566,93.9848,Não
157,158,cliente,Cliente_130,Receita Total,"38,298.0268",4,0.2520,94.2369,Não
158,159,cliente,Cliente_022,Receita Total,"38,011.7517",6,0.2501,94.4870,Não
159,160,cliente,Cliente_063,Receita Total,"38,008.0548",3,0.2501,94.7371,Não
160,161,cliente,Cliente_132,Receita Total,"38,003.8459",5,0.2501,94.9872,Não
161,162,cliente,Cliente_156,Receita Total,"37,609.3822",4,0.2475,95.2347,Não
162,163,cliente,Cliente_152,Receita Total,"37,282.3647",2,0.2453,95.4800,Não
163,164,cliente,Cliente_196,Receita Total,"36,814.1461",6,0.2423,95.7223,Não
164,165,cliente,Cliente_030,Receita Total,"36,407.5892",3,0.2396,95.9619,Não
165,166,cliente,Cliente_070,Receita Total,"36,004.9548",4,0.2369,96.1988,Não
166,167,cliente,Cliente_131,Receita Total,"35,011.0052",3,0.2304,96.4292,Não
167,168,cliente,Cliente_182,Receita Total,"34,814.4171",6,0.2291,96.6583,Não
168,169,cliente,Cliente_074,Receita Total,"32,930.9761",3,0.2167,96.8750,Não
169,170,cliente,Cliente_146,Receita Total,"31,962.1531",4,0.2103,97.0854,Não
170,171,cliente,Cliente_079,Receita Total,"28,060.8909",3,0.1847,97.2700,Não
171,172,cliente,Cliente_042,Receita Total,"27,375.6854",4,0.1801,97.4502,Não
172,173,cliente,Cliente_069,Receita Total,"27,323.0806",3,0.1798,97.6300,Não
173,174,cliente,Cliente_056,Receita Total,"26,758.8728",3,0.1761,97.8061,Não
174,175,cliente,Cliente_145,Receita Total,"26,661.6108",2,0.1755,97.9815,Não
175,176,cliente,Cliente_055,Receita Total,"26,549.5316",3,0.1747,98.1562,Não
176,177,cliente,Cliente_010,Receita Total,"25,869.2922",2,0.1702,98.3265,Não
177,178,cliente,Cliente_007,Receita Total,"25,758.1486",3,0.1695,98.4960,Não
178,179,cliente,Cliente_073,Receita Total,"24,326.2800",1,0.1601,98.6560,Não
179,180,cliente,Cliente_050,Receita Total,"21,981.5699",4,0.1447,98.8007,Não
180,181,cliente,Cliente_068,Receita Total,"20,656.0116",4,0.1359,98.9366,Não
181,182,cliente,Cliente_103,Receita Total,"18,228.1794",4,0.1200,99.0566,Não
182,183,cliente,Cliente_004,Receita Total,"17,727.8042",3,0.1167,99.1732,Não
183,184,cliente,Cliente_003,Receita Total,"16,570.0445",4,0.1090,99.2823,Não
184,185,cliente,Cliente_026,Receita Total,"15,795.2096",2,0.1039,99.3862,Não
185,186,cliente,Cliente_190,Receita Total,"13,837.8511",4,0.0911,99.4773,Não
186,187,cliente,Cliente_038,Receita Total,"13,266.5035",3,0.0873,99.5646,Não
187,188,cliente,Cliente_177,Receita Total,"8,854.4225",1,0.0583,99.6229,Não
188,189,cliente,Cliente_105,Receita Total,"7,316.3297",2,0.0481,99.6710,Não
189,190,cliente,Cliente_157,Receita Total,"7,313.8464",1,0.0481,99.7191,Não
190,191,cliente,Cliente_200,Receita Total,"6,246.0600",1,0.0411,99.7602,Não
191,192,cliente,Cliente_166,Receita Total,"5,860.2954",2,0.0386,99.7988,Não
192,193,cliente,Cliente_039,Receita Total,"5,587.6440",2,0.0368,99.8356,Não
193,194,cliente,Cliente_101,Receita Total,"5,372.4847",3,0.0354,99.8709,Não
194,195,cliente,Cliente_015,Receita Total,"4,823.6544",1,0.0317,99.9027,Não
195,196,cliente,Cliente_072,Receita Total,"4,256.2988",1,0.0280,99.9307,Não
196,197,cliente,Cliente_191,Receita Total,"4,186.0962",1,0.0275,99.9582,Não
197,198,cliente,Cliente_006,Receita Total,"3,671.4015",2,0.0242,99.9824,Não
198,199,cliente,Cliente_076,Receita Total,"2,677.8804",1,0.0176,100.0000,Não

In [58]:
# PARETO - PRODUTO VS. RECEITA TOTAL
# ============================================================

pareto_produto_receita = analise_pareto(
    base=df,
    dimensao="produto",
    metrica="receita",
    nome_metrica="Receita Total"
)

pareto_produto_receita

,ranking,dimensao_analisada,produto,metrica_analisada,valor_total,quantidade_registros,participacao_%,participacao_acumulada_%,grupo_pareto_80
0,1,produto,Monitor,Receita Total,"2,463,025.3196",143,16.2083,16.2083,Sim
1,2,produto,Teclado,Receita Total,"1,973,461.4424",115,12.9866,29.1949,Sim
2,3,produto,Mouse,Receita Total,"1,962,335.2508",133,12.9134,42.1083,Sim
3,4,produto,Smartphone,Receita Total,"1,946,475.0212",133,12.8090,54.9173,Sim
4,5,produto,Impressora,Receita Total,"1,859,469.9215",115,12.2365,67.1538,Sim
5,6,produto,Headset,Receita Total,"1,697,277.7110",111,11.1692,78.3229,Sim
6,7,produto,Notebook,Receita Total,"1,647,800.9065",122,10.8436,89.1665,Sim
7,8,produto,Tablet,Receita Total,"1,646,272.9057",128,10.8335,100.0000,Não

In [57]:
# RESUMO CONSOLIDADO DAS ANÁLISES DE PARETO
# ============================================================

analises_pareto = {
    "Produto vs. Lucro": pareto_produto_lucro,
    "Categoria vs. Lucro": pareto_categoria_lucro,
    "Região vs. Lucro": pareto_regiao_lucro,
    "Vendedor vs. Lucro": pareto_vendedor_lucro,
    "Marca vs. Lucro": pareto_marca_lucro,
    "Linha de Produto vs. Lucro": pareto_linha_lucro,
    "Cliente vs. Receita": pareto_cliente_receita,
    "Cliente vs. Lucro": pareto_cliente_lucro,
    "Produto vs. Receita": pareto_produto_receita
}

resumo_pareto = []

for nome_analise, tabela in analises_pareto.items():
    grupo_80 = tabela[tabela["grupo_pareto_80"] == "Sim"]

    resumo_pareto.append({
        "analise": nome_analise,
        "total_itens": tabela.shape[0],
        "itens_no_grupo_80": grupo_80.shape[0],
        "percentual_itens_no_grupo_80": grupo_80.shape[0] / tabela.shape[0] * 100,
        "participacao_acumulada_grupo_80": grupo_80["participacao_acumulada_%"].max()
    })

resumo_pareto = pd.DataFrame(resumo_pareto)

resumo_pareto

,analise,total_itens,itens_no_grupo_80,percentual_itens_no_grupo_80,participacao_acumulada_grupo_80
0,Produto vs. Lucro,8,6,75.0000,80.1971
1,Categoria vs. Lucro,4,2,50.0000,84.1775
2,Região vs. Lucro,5,4,80.0000,82.8837
3,Vendedor vs. Lucro,20,15,75.0000,82.9963
4,Marca vs. Lucro,4,4,100.0000,100.0000
5,Linha de Produto vs. Lucro,3,3,100.0000,100.0000
6,Cliente vs. Receita,199,118,59.2965,80.3856
7,Cliente vs. Lucro,199,102,51.2563,80.0956
8,Produto vs. Receita,8,7,87.5000,89.1665

## Etapa 4.3 - Análise de Pareto 80/20

Nesta etapa foi aplicada a Análise de Pareto, também conhecida como regra 80/20, com o objetivo de identificar quais elementos concentram a maior parte dos resultados da empresa. A lógica da análise consiste em ordenar os itens do maior para o menor valor, calcular a participação percentual de cada item no total e, em seguida, calcular a participação acumulada.

Foram realizadas análises de Pareto para diferentes dimensões do negócio, como produto, categoria, região, vendedor, marca, linha de produto e cliente. As principais métricas utilizadas foram lucro total e receita total.

Na análise de produto versus lucro total, observou-se que seis dos oito produtos concentram aproximadamente 80% do lucro da empresa. Isso indica que o lucro está relativamente distribuído entre os produtos, embora alguns itens tenham maior peso no resultado financeiro.

Na análise por categoria, o comportamento de Pareto apareceu de forma mais clara. As categorias Informática e Periféricos concentraram aproximadamente 84% do lucro total. Isso mostra que essas duas categorias são as principais responsáveis pela geração de resultado financeiro da empresa e devem ser priorizadas em estratégias comerciais, campanhas e gestão de estoque.

Na análise regional, verificou-se que quatro das cinco regiões são necessárias para atingir cerca de 80% do lucro. Isso indica que o lucro está distribuído geograficamente, sem dependência extrema de uma única região.

Na análise por vendedor, aproximadamente quinze dos vinte vendedores explicam cerca de 80% do lucro. Esse resultado mostra que o desempenho comercial está relativamente distribuído entre a equipe, embora os vendedores mais bem posicionados devam ser analisados para identificação de boas práticas.

A análise por marca mostrou que a marca Alpha possui a maior participação no lucro, mas as demais marcas também possuem contribuição relevante. Portanto, não há dependência extrema de uma única marca. Já na análise por linha de produto, as linhas Econômico, Premium e Padrão apresentaram contribuições próximas, indicando equilíbrio entre os diferentes padrões de produto.

Também foi realizada a análise de Pareto por cliente em relação à receita e ao lucro. Essa análise é importante para avaliar concentração da carteira. Quando poucos clientes concentram grande parte da receita ou do lucro, existe maior risco comercial. Quando muitos clientes são necessários para atingir 80%, a empresa possui uma carteira mais distribuída.

Conclui-se que a Análise de Pareto permitiu identificar os principais focos estratégicos da empresa. As categorias Informática e Periféricos são os grupos mais relevantes para o lucro, enquanto produtos, regiões, marcas e vendedores apresentam distribuição mais equilibrada. Essa análise apoia decisões sobre priorização de campanhas, alocação de recursos, gestão de estoque, relacionamento com clientes e avaliação de desempenho comercial.